force-app/main/default/objects/Project_Location_GEO__c/Project_Location_GEO__c.object-meta.xml
<CustomObject>
    <label>Project Location GEO</label>
    <nameField>
        <label>Project Location ZIP Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Location GEO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Location_GEO__c/fields/County_Name__c.field-meta.xml
<CustomField>
    <fullName>County_Name__c</fullName>
    <label>County Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Location_GEO__c/fields/Lat__c.field-meta.xml
<CustomField>
    <fullName>Lat__c</fullName>
    <label>Lat</label>
    <precision>8</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Location_GEO__c/fields/Long__c.field-meta.xml
<CustomField>
    <fullName>Long__c</fullName>
    <label>Long</label>
    <precision>8</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Location_GEO__c/fields/State_Abbr__c.field-meta.xml
<CustomField>
    <fullName>State_Abbr__c</fullName>
    <label>State Abbr</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Location_GEO__c/fields/State_Name__c.field-meta.xml
<CustomField>
    <fullName>State_Name__c</fullName>
    <label>State Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Location_GEO__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SG_ProjectLocation_Test.cls
/**********************************************************************
* Name:     SG_ProjectLocation_Test
* Author:   Strategic Growth, Inc. (www.strategicgrowthinc.com)
*  
* ======================================================
* ======================================================
* Purpose:                                                      
* 
* ======================================================
* ======================================================
* History:                                                            
* VERSION   DATE            INITIALS      DESCRIPTION/FEATURES ADDED
* 1.0       23-Oct-2019     rwd           Initial Development           
*   
***********************************************************************/


@IsTest
private class SG_ProjectLocation_Test {

	private static SG_TestDataGenerator td;
	private static List<Account> accounts;
	private static List<Opportunity> opps;
	private static List<Project_Location_GEO__c> geos;


	@testSetup static void setupTestData()
	{
		td = new SG_TestDataGenerator();
		accounts = td.getAccounts(true);
		opps = td.getOpportunities(true);
		geos = td.getGeos(true);

	}

	static testMethod void testBehavior()
	{
		refreshData();

		// set the opp...
		Opportunity o = opps[0];
		System.assertEquals( o.Project_Location_City__c, null);

		SG_OpportunityHelper.hasDoneZip = false;
		o.Project_Location_Zip__c = geos[0].Id;
		o.Entity__c = 'Arlun';
		update o;

		refreshData();

		o = opps[0];
		System.debug(LoggingLevel.WARN, '---> in test; o: ' + o );
		System.debug(LoggingLevel.WARN, '---> opp city: ' + o.Project_Location_City__c );
		System.debug(LoggingLevel.WARN, '---> geos city: ' + geos[0].City__c );
		System.assertEquals( o.Project_Location_City__c, geos[0].City__c);

		// now test the page...
		PageReference theScreen = Page.SG_ProjectLocation;
		Test.setCurrentPage( theScreen );
		System.currentPageReference().getParameters().put('id', o.Id);

		ApexPages.StandardController con = new ApexPages.Standardcontroller( o );
		SG_VFC_ProjectLocation controller = new SG_VFC_ProjectLocation( con );

		// blank out the entity and re-run
		System.debug(LoggingLevel.WARN, '---> blank out entity and retest');
		o.Entity__c = null;
		update o;
		refreshData();
		o = opps[0];
		ApexPages.StandardController con2 = new ApexPages.Standardcontroller( o );
		SG_VFC_ProjectLocation controller2 = new SG_VFC_ProjectLocation( con2 );
		controller2.doQuery();

		// finally - blank out the opp location
		o.Project_Location_Zip__c = null;
		SG_OpportunityHelper.hasDoneZip = false;
		update o;
		refreshData();

		o = opps[0];
		System.assertEquals( o.Project_Location_City__c, null);

		// verify trigger shut off...
		SG_OpportunityHelper.isTest = true;
		SG_OpportunityHelper.hasDoneZip = false;
		o.Project_Location_Zip__c = geos[0].Id;
		update o;
		refreshData();

		o = opps[0];
		System.assertEquals( o.Project_Location_City__c, null);
	}

	public static void refreshData() {

		accounts = [SELECT Id, Name FROM Account];
		opps = [SELECT Id, Name, Project_Location_GEO__latitude__s,Project_Location_GEO__longitude__s, Project_Location_Zip__c, Project_Location_City__c, IsClosed, IsWon, Project_Location_State__c FROM Opportunity];
		geos = [SELECT Id, Name, City__c, County_Name__c, Lat__c, Long__c, State_Abbr__c, State_Name__c, Time_Zone__c FROM Project_Location_GEO__c];
	}


}