force-app/main/default/objects/RollupConfigs__c/RollupConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RollupConfigs</label>
</CustomObject>

force-app/main/default/objects/RollupConfigs__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>On/Off toggle for this particular configuration</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/Child_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_Object_Name__c</fullName>
    <description>Stores the API name of the child object which contains fields to be rolled up by the Parent</description>
    <inlineHelpText>Stores the API name of the child object which contains fields to be rolled up by the Parent</inlineHelpText>
    <label>Child Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <description>Stores the API name of the Parent object which will display the roll-up summaries of lookup fields</description>
    <inlineHelpText>Stores the API name of the Parent object which will display the roll-up summaries of lookup fields</inlineHelpText>
    <label>Parent Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/parentQueryField1__c.field-meta.xml
<CustomField>
    <fullName>parentQueryField1__c</fullName>
    <description>Holds the API name of the field on the Parent object which will display the rolled-up summary of fields on the Child. Example: total_hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Parent object which will display the rolled-up summary of fields on the Child. Example: total_hours_spent__c</inlineHelpText>
    <label>parentQueryField1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/parentQueryField2__c.field-meta.xml
<CustomField>
    <fullName>parentQueryField2__c</fullName>
    <description>Holds the API name of the field on the Parent object which will display the rolled-up summary of fields on the Child. Example: total_hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Parent object which will display the rolled-up summary of fields on the Child. Example: total_hours_spent__c</inlineHelpText>
    <label>parentQueryField2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/parentQueryField3__c.field-meta.xml
<CustomField>
    <fullName>parentQueryField3__c</fullName>
    <description>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</inlineHelpText>
    <label>parentQueryField3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/parentQueryField4__c.field-meta.xml
<CustomField>
    <fullName>parentQueryField4__c</fullName>
    <description>Holds the API name of the field on the Parent object which will display the rolled-up summary of fields on the Child. Example: total_hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Parent object which will display the rolled-up summary of fields on the Child. Example: total_hours_spent__c</inlineHelpText>
    <label>parentQueryField4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/parentQueryField5__c.field-meta.xml
<CustomField>
    <fullName>parentQueryField5__c</fullName>
    <description>Holds the API name of the field on the Parent object which will display the rolled-up summary of fields on the Child. Example: total_hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Parent object which will display the rolled-up summary of fields on the Child. Example: total_hours_spent__c</inlineHelpText>
    <label>parentQueryField5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/parentRowCount__c.field-meta.xml
<CustomField>
    <fullName>parentRowCount__c</fullName>
    <description>Holds the API name of the field on the parent which stores the aggregated number of child rows (e.g., if there are 15 children for a parent, value will be &quot;15&quot;)</description>
    <inlineHelpText>Holds the API name of the field on the parent which stores the aggregated number of child rows (e.g., if there are 15 children for a parent, value will be &quot;15&quot;)</inlineHelpText>
    <label>parentRowCount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/queryField1__c.field-meta.xml
<CustomField>
    <fullName>queryField1__c</fullName>
    <description>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</inlineHelpText>
    <label>queryField1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/queryField2__c.field-meta.xml
<CustomField>
    <fullName>queryField2__c</fullName>
    <description>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</inlineHelpText>
    <label>queryField2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/queryField3__c.field-meta.xml
<CustomField>
    <fullName>queryField3__c</fullName>
    <description>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</inlineHelpText>
    <label>queryField3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/queryField4__c.field-meta.xml
<CustomField>
    <fullName>queryField4__c</fullName>
    <description>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</inlineHelpText>
    <label>queryField4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/queryField5__c.field-meta.xml
<CustomField>
    <fullName>queryField5__c</fullName>
    <description>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</inlineHelpText>
    <label>queryField5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/queryField_parentRelationshipName__c.field-meta.xml
<CustomField>
    <fullName>queryField_parentRelationshipName__c</fullName>
    <description>Holds the API name of the field on the Child that is the Lookup relationship to the parent. Example: parent_account__c</description>
    <inlineHelpText>Holds the API name of the field on the Child that is the Lookup relationship to the parent. Example: parent_account__c</inlineHelpText>
    <label>queryField_parentRelationshipName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SG_TDG_LookupRollupSummary.cls
/**********************************************************************
* Name:   	SG_TDG_LookupRollupSummary
* Author: 	Strategic Growth, Inc. (www.strategicgrowthinc.com)
* Date: 	2009
* ======================================================
* ======================================================
* Purpose:                                                            
* This class is used to create test data. It is virtual so that it can be extended
*                                                            
* ======================================================
* ======================================================
* History:                                                            
* VERSION	DATE            INITIALS	DESCRIPTION/FEATURES ADDED
* 1.0     	2009	        CS			Initial Development           
*   
***********************************************************************/

@isTest
public class SG_TDG_LookupRollupSummary extends SG_TestDataGenerator 
{
	private RollupConfigs__c config; 
	
	public SG_TDG_LookupRollupSummary(){ 
		super();
	}
	
	public RollupConfigs__c getRollupConfiguration() {
		if(config == null) {
			List<RollupConfigs__c> existingContactAccountConfig = [SELECT Id 
																   FROM RollupConfigs__c 
																   WHERE Child_Object_Name__c = 'Contact' 
																   AND Parent_Object__c = 'Account'];
			if(existingContactAccountConfig != null && existingContactAccountConfig.size() == 1) {
				config = existingContactAccountConfig[0];
			} else {
				config = new RollupConfigs__c();
			}
			config.Child_Object_Name__c = 'Contact';
			config.Parent_Object__c = 'Account';
			config.Name = 'ContactToAccount';
			config.parentRowCount__c = 'NumberOfEmployees';
			config.queryField_parentRelationshipName__c = 'AccountId';
			config.queryField1__c = 'Unit_Contact__c';
			config.queryField2__c = null;
			config.queryField3__c = null;
			config.queryField4__c = null;
			config.queryField5__c = null;
			config.parentQueryField1__c = 'Description';
			config.parentQueryField2__c = null;
			config.parentQueryField3__c = null;
			config.parentQueryField4__c = null;
			config.parentQueryField5__c = null;
			config.Active__c = true;
			
			if(config.Id == null) {
				insert config;
			} else {
				update config;
			}
		}
		return config;
	}


	public override void initAllTestData() 
	{			
		super.initAllTestData();
		getRollupConfiguration();				
	}    
}