force-app/main/default/objects/RollupConfigs__c/RollupConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RollupConfigs</label>
</CustomObject>

force-app/main/default/objects/RollupConfigs__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>On/Off toggle for this particular configuration</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/Additional_Filter_Clause__c.field-meta.xml
<CustomField>
    <fullName>Additional_Filter_Clause__c</fullName>
    <inlineHelpText>Add an optional filter clause to the rollup, without quotes or punctuation. Example: AND IsActive = true</inlineHelpText>
    <label>Additional Filter Clause</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/Child_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_Object_Name__c</fullName>
    <description>Stores the API name of the child object which contains fields to be rolled up by the Parent</description>
    <inlineHelpText>Stores the API name of the child object which contains fields to be rolled up by the Parent</inlineHelpText>
    <label>Child Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/Config_Notes__c.field-meta.xml
<CustomField>
    <fullName>Config_Notes__c</fullName>
    <inlineHelpText>Optional notes about this configuration (special modifications to the trigger, explanations, etc)</inlineHelpText>
    <label>Config Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/Date_Math_Query_Type__c.field-meta.xml
<CustomField>
    <fullName>Date_Math_Query_Type__c</fullName>
    <inlineHelpText>For aggregating queries - stores value of MAX/MIN/AVG</inlineHelpText>
    <label>Date/Math Query Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/Do_Date_Query__c.field-meta.xml
<CustomField>
    <fullName>Do_Date_Query__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked will perform an aggregate DATE query for all configured rollups (ex: MAX(CloseDate)). Use a separate rollup configuration for &quot;normal&quot; rollups.</inlineHelpText>
    <label>Do Date Query</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/Do_Date_Time_Query__c.field-meta.xml
<CustomField>
    <fullName>Do_Date_Time_Query__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked will perform an aggregate DATETIME query for all configured rollups (ex: MAX(CreatedDate)). Use a separate rollup configuration for &quot;normal&quot; rollups.</inlineHelpText>
    <label>Do Date/Time Query</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/Do_Math_Query__c.field-meta.xml
<CustomField>
    <fullName>Do_Math_Query__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked will perform an aggregate NUMERIC query for all configured rollups (ex: MAX(Amount)). Use a separate rollup configuration for &quot;normal&quot; rollups.</inlineHelpText>
    <label>Do Math Query</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <description>Stores the API name of the Parent object which will display the roll-up summaries of lookup fields</description>
    <inlineHelpText>Stores the API name of the Parent object which will display the roll-up summaries of lookup fields</inlineHelpText>
    <label>Parent Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/parentQueryField1__c.field-meta.xml
<CustomField>
    <fullName>parentQueryField1__c</fullName>
    <description>Holds the API name of the field on the Parent object which will display the rolled-up summary of fields on the Child. Example: total_hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Parent object which will display the rolled-up summary of fields on the Child. Example: total_hours_spent__c</inlineHelpText>
    <label>parentQueryField1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/parentQueryField2__c.field-meta.xml
<CustomField>
    <fullName>parentQueryField2__c</fullName>
    <description>Holds the API name of the field on the Parent object which will display the rolled-up summary of fields on the Child. Example: total_hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Parent object which will display the rolled-up summary of fields on the Child. Example: total_hours_spent__c</inlineHelpText>
    <label>parentQueryField2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/parentQueryField3__c.field-meta.xml
<CustomField>
    <fullName>parentQueryField3__c</fullName>
    <description>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</inlineHelpText>
    <label>parentQueryField3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/parentQueryField4__c.field-meta.xml
<CustomField>
    <fullName>parentQueryField4__c</fullName>
    <description>Holds the API name of the field on the Parent object which will display the rolled-up summary of fields on the Child. Example: total_hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Parent object which will display the rolled-up summary of fields on the Child. Example: total_hours_spent__c</inlineHelpText>
    <label>parentQueryField4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/parentQueryField5__c.field-meta.xml
<CustomField>
    <fullName>parentQueryField5__c</fullName>
    <description>Holds the API name of the field on the Parent object which will display the rolled-up summary of fields on the Child. Example: total_hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Parent object which will display the rolled-up summary of fields on the Child. Example: total_hours_spent__c</inlineHelpText>
    <label>parentQueryField5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/parentRowCount__c.field-meta.xml
<CustomField>
    <fullName>parentRowCount__c</fullName>
    <description>Holds the API name of the field on the parent which stores the aggregated number of child rows (e.g., if there are 15 children for a parent, value will be &quot;15&quot;)</description>
    <inlineHelpText>Holds the API name of the field on the parent which stores the aggregated number of child rows (e.g., if there are 15 children for a parent, value will be &quot;15&quot;)</inlineHelpText>
    <label>parentRowCount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/queryField1__c.field-meta.xml
<CustomField>
    <fullName>queryField1__c</fullName>
    <description>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</inlineHelpText>
    <label>queryField1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/queryField2__c.field-meta.xml
<CustomField>
    <fullName>queryField2__c</fullName>
    <description>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</inlineHelpText>
    <label>queryField2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/queryField3__c.field-meta.xml
<CustomField>
    <fullName>queryField3__c</fullName>
    <description>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</inlineHelpText>
    <label>queryField3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/queryField4__c.field-meta.xml
<CustomField>
    <fullName>queryField4__c</fullName>
    <description>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</inlineHelpText>
    <label>queryField4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/queryField5__c.field-meta.xml
<CustomField>
    <fullName>queryField5__c</fullName>
    <description>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</description>
    <inlineHelpText>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</inlineHelpText>
    <label>queryField5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/queryField_parentRelationshipName__c.field-meta.xml
<CustomField>
    <fullName>queryField_parentRelationshipName__c</fullName>
    <description>Holds the API name of the field on the Child that is the Lookup relationship to the parent. Example: parent_account__c</description>
    <inlineHelpText>Holds the API name of the field on the Child that is the Lookup relationship to the parent. Example: parent_account__c</inlineHelpText>
    <label>queryField_parentRelationshipName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupConfigs__c/fields/Use_Queueable__c.field-meta.xml
<CustomField>
    <fullName>Use_Queueable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, rollup helper will execute as asynchronous and queueable. This will help with large data volumes, but may take several seconds (or even minutes) for results to appear in Salesforce.</inlineHelpText>
    <label>Use Queueable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SG_VFC_LRHSetup_Test.cls
/**********************************************************************
* Name:     SG_VFC_LRHSetup_Test
* Author:   Strategic Growth, Inc. (www.strategicgrowthinc.com)
*  
* ======================================================
* ======================================================
* Purpose:                                                      
* 
* ======================================================
* ======================================================
* History:                                                            
* VERSION   DATE            INITIALS      DESCRIPTION/FEATURES ADDED
* 1.0       12-Sep-2018     rwd           Initial Development           
*   
***********************************************************************/


@IsTest
private class SG_VFC_LRHSetup_Test
{

	private static SG_TDG_LookupRollupSummary td;
	private static List<Account> accounts;
	private static List<Contact> contacts;
	private static List<RollupConfigs__c> rollupConfigs;


	@testSetup static void setupTestData()
	{
		td = new SG_TDG_LookupRollupSummary();
		td.accountNum = 1;
		accounts = td.getAccounts(true);
		contacts = td.getContacts(true);


	}

	static testMethod void testCreate()
	{
		td = new SG_TDG_LookupRollupSummary();
		refreshData();


		RollupConfigs__c config = new RollupConfigs__c();
		PageReference theScreen = Page.SG_LRHSetup;
    	Test.setCurrentPage(theScreen);
    	//System.currentPageReference().getParameters().put('acctId', a.Id);
    	
    	ApexPages.StandardController con = new ApexPages.Standardcontroller( config );
    	SG_VFC_LRHSetup controller = new SG_VFC_LRHSetup( con );

		// create a new mapping
		controller.doShowCreateSection();
		controller.childObject = 'Contact';
		controller.parentObject = 'Account';
		controller.setObjects();

		System.assertNotEquals(null, controller.theConfig );
		System.assertNotEquals( null, controller.theConfig.Name );

		controller.doShowTriggerReload();

		// configure the mapping
		controller.theConfig.queryField_parentRelationshipName__c = 'AccountId';
		controller.theConfig.parentRowCount__c = 'NumberOfEmployees';

		controller.saveConfig();

		refreshData();
		System.assertEquals( rollupConfigs[0].Parent_Object__c, 'Account' );
		System.assertEquals( rollupConfigs[0].Child_Object_Name__c, 'Contact' );

		List<Contact> newContacts = new List<Contact>();
		for ( Contact c : contacts )
		{
			c.FirstName = 'Test';
			newContacts.add( c );
		}
		upsert newContacts;

		// fire the rollup...
		//Pass in the API name of the child object, for example 'Contact' and the API name of the parent object, for example 'Account';
		SG_LookupRollupHelper lh = new SG_LookupRollupHelper( 'Contact', 'Account');

		// take care of assigning the correct lists based on the trigger type (Insert vs Update vs Delete vs Undelete)
		lh.setTriggerLists(true, false, newContacts, contacts);

		// do the rollup(s) -- will execute all active rollups for current child/parent configuration
		lh.doRollupSummary();


	}

	static testMethod void testEdit()
	{
		td = new SG_TDG_LookupRollupSummary();
		refreshData();

		RollupConfigs__c config = new RollupConfigs__c();
		PageReference theScreen = Page.SG_LRHSetup;
		Test.setCurrentPage(theScreen);
		//System.currentPageReference().getParameters().put('acctId', a.Id);

		ApexPages.StandardController con = new ApexPages.Standardcontroller( config );
		SG_VFC_LRHSetup controller = new SG_VFC_LRHSetup( con );

		// create a new mapping
		controller.doShowCreateSection();
		controller.childObject = 'Contact';
		controller.parentObject = 'Account';
		controller.setObjects();

		System.assertNotEquals(null, controller.theConfig );
		System.assertNotEquals( null, controller.theConfig.Name );

		// configure the mapping
		controller.theConfig.queryField_parentRelationshipName__c = 'AccountId';
		controller.saveConfig();

		refreshData();

		// edit the existing mapping
		controller.childObject = rollupConfigs[0].Child_Object_Name__c;
		controller.parentObject = rollupConfigs[0].Parent_Object__c;
		controller.selectedConfigName = rollupConfigs[0].Name;
		controller.doEdit = 'true';
		controller.editConfiguration();

		// make it inactive and show a trigger...
		System.assertEquals(true, controller.theConfig.Active__c);

		controller.theConfig.Active__c = false;
		//controller.theConfig.Create_Trigger__c = true;
		controller.saveConfig();

		refreshData();
		System.assertNotEquals(true, controller.theConfig.Active__c);

		// now lets click some boxes to fire the refresh methods...
		controller.theConfig.Do_Math_Query__c = true;
		controller.doMathQuerySelect();

		controller.theConfig.Do_Date_Query__c = true;
		controller.doDateSelect();

		controller.theConfig.Do_Date_Time_Query__c = true;
		controller.doDateTimeSelect();

		controller.customCancel();
	}


	static testMethod void testDelete()
	{
		td = new SG_TDG_LookupRollupSummary();
		refreshData();

		RollupConfigs__c config = new RollupConfigs__c();
		PageReference theScreen = Page.SG_LRHSetup;
		Test.setCurrentPage(theScreen);
		//System.currentPageReference().getParameters().put('acctId', a.Id);

		ApexPages.StandardController con = new ApexPages.Standardcontroller( config );
		SG_VFC_LRHSetup controller = new SG_VFC_LRHSetup( con );

		// create a new mapping
		controller.doShowCreateSection();
		controller.childObject = 'Contact';
		controller.parentObject = 'Account';
		controller.setObjects();

		System.assertNotEquals(null, controller.theConfig );
		System.assertNotEquals( null, controller.theConfig.Name );

		// configure the mapping
		controller.theConfig.queryField_parentRelationshipName__c = 'AccountId';
		controller.saveConfig();

		refreshData();

		// delete the existing mapping
		controller.deleteConfig();

		refreshData();
		//System.assertEquals(null, controller.theConfig);
	}

	static testMethod void testQueueable()
	{
		td = new SG_TDG_LookupRollupSummary();
		refreshData();


		//Pass in the API name of the child object, for example 'Contact' and the API name of the parent object, for example 'Account';
		SG_LookupRollupHelper lh = new SG_LookupRollupHelper( 'Contact', 'Account');

		List<Contact> contacts2 = new List<Contact>();
		for ( Contact c : contacts )
		{
			c.FirstName = 'NEW';
			contacts2.add( c );
		}

		// take care of assigning the correct lists based on the trigger type (Insert vs Update vs Delete vs Undelete)
		lh.setTriggerLists(false, false, contacts2, contacts);


		RollupConfigs__c config = new RollupConfigs__c();
		PageReference theScreen = Page.SG_LRHSetup;
		Test.setCurrentPage(theScreen);
		//System.currentPageReference().getParameters().put('acctId', a.Id);

		ApexPages.StandardController con = new ApexPages.Standardcontroller( config );
		SG_VFC_LRHSetup controller = new SG_VFC_LRHSetup( con );

		// create a new mapping
		controller.doShowCreateSection();
		controller.childObject = 'Contact';
		controller.parentObject = 'Account';
		controller.setObjects();

		System.assertNotEquals(null, controller.theConfig );
		System.assertNotEquals( null, controller.theConfig.Name );

		// configure the mapping
		controller.theConfig.queryField_parentRelationshipName__c = 'AccountId';
		controller.theConfig.Use_Queueable__c = true;
		controller.theConfig.Additional_Filter_Clause__c = ' AND CreatedDate != null ';
		controller.saveConfig();

		refreshData();
		// fire the rollup...
		lh.mappingToUse = controller.theConfig.Name;
		lh.doRollupSummary();

	}

	static testMethod void testDateRollup()
	{
		td = new SG_TDG_LookupRollupSummary();
		refreshData();


		RollupConfigs__c config = new RollupConfigs__c();
		PageReference theScreen = Page.SG_LRHSetup;
		Test.setCurrentPage(theScreen);
		//System.currentPageReference().getParameters().put('acctId', a.Id);

		ApexPages.StandardController con = new ApexPages.Standardcontroller( config );
		SG_VFC_LRHSetup controller = new SG_VFC_LRHSetup( con );

		// create a new mapping
		controller.doShowCreateSection();
		controller.childObject = 'Contact';
		controller.parentObject = 'Account';
		controller.setObjects();

		System.assertNotEquals(null, controller.theConfig );
		System.assertNotEquals( null, controller.theConfig.Name );

		// configure the mapping

		controller.theConfig.Use_Queueable__c = false;
		controller.theConfig.Additional_Filter_Clause__c = ' AND CreatedDate != null ';

		// set the right box
		controller.theConfig.Do_Date_Query__c = true;

		// let's get a bonus valiation test...
		controller.theConfig.queryField_parentRelationshipName__c = null;
		controller.theConfig.Date_Math_Query_Type__c = null;
		controller.saveConfig();

		refreshData();
		Map<String, RollupConfigs__c> configMap = RollupConfigs__c.getAll();
		System.debug(LoggingLevel.WARN, '---> in testDateRollup; configMap after failed validation test: ' + configMap );
		System.assertEquals( 0, configMap.keySet().size() );

		// let's save for real...
		controller.theConfig.queryField_parentRelationshipName__c = 'AccountId';
		controller.theConfig.Date_Math_Query_Type__c = 'MAX';
		controller.theConfig.parentQueryField1__c = 'Site';

		// set up some bogus fields...
		controller.theConfig.queryField1__c = 'Birthdate';
		controller.theConfig.parentQueryField1__c = 'NumberOfEmployees';
		controller.saveConfig();

		refreshData();

		configMap = RollupConfigs__c.getAll();
		System.debug(LoggingLevel.WARN, '---> in testDateRollup; configMap is now: ' + configMap );


		// fire the rollup...
		//Pass in the API name of the child object, for example 'Contact' and the API name of the parent object, for example 'Account';
		SG_LookupRollupHelper lh = new SG_LookupRollupHelper( 'Contact', 'Account');

		// take care of assigning the correct lists based on the trigger type (Insert vs Update vs Delete vs Undelete)
		lh.setTriggerLists(true, false, contacts, null);
		lh.doDateQuery = true;
		lh.dateMathQueryType = 'MAX';

		// do the rollup(s) -- will execute all active rollups for current child/parent configuration
		lh.doRollupSummary();

	}

	static testMethod void testDateTimeRollup()
	{
		td = new SG_TDG_LookupRollupSummary();
		refreshData();


		RollupConfigs__c config = new RollupConfigs__c();
		PageReference theScreen = Page.SG_LRHSetup;
		Test.setCurrentPage(theScreen);
		//System.currentPageReference().getParameters().put('acctId', a.Id);

		ApexPages.StandardController con = new ApexPages.Standardcontroller( config );
		SG_VFC_LRHSetup controller = new SG_VFC_LRHSetup( con );

		// create a new mapping
		controller.doShowCreateSection();
		controller.childObject = 'Contact';
		controller.parentObject = 'Account';
		controller.setObjects();

		System.assertNotEquals(null, controller.theConfig );
		System.assertNotEquals( null, controller.theConfig.Name );

		// configure the mapping

		controller.theConfig.Use_Queueable__c = false;
		controller.theConfig.Additional_Filter_Clause__c = ' AND CreatedDate != null ';

		// set the right box
		controller.theConfig.Do_Date_Time_Query__c = true;

		controller.theConfig.queryField_parentRelationshipName__c = 'AccountId';
		controller.theConfig.Date_Math_Query_Type__c = 'MAX';

		// set up some bogus fields...
		controller.theConfig.queryField1__c = 'CreatedDate';
		controller.theConfig.parentQueryField1__c = 'NumberOfEmployees';

		controller.saveConfig();

		refreshData();

		// fire the rollup...
		//Pass in the API name of the child object, for example 'Contact' and the API name of the parent object, for example 'Account';
		SG_LookupRollupHelper lh = new SG_LookupRollupHelper( 'Contact', 'Account');

		// take care of assigning the correct lists based on the trigger type (Insert vs Update vs Delete vs Undelete)
		lh.setTriggerLists(true, false, contacts, null);


		// do the rollup(s) -- will execute all active rollups for current child/parent configuration
		lh.doRollupSummary();

	}

	static testMethod void testMathRollup()
	{
		td = new SG_TDG_LookupRollupSummary();
		refreshData();


		RollupConfigs__c config = new RollupConfigs__c();
		PageReference theScreen = Page.SG_LRHSetup;
		Test.setCurrentPage(theScreen);
		//System.currentPageReference().getParameters().put('acctId', a.Id);

		ApexPages.StandardController con = new ApexPages.Standardcontroller( config );
		SG_VFC_LRHSetup controller = new SG_VFC_LRHSetup( con );

		// create a new mapping
		controller.doShowCreateSection();
		controller.childObject = 'Contact';
		controller.parentObject = 'Account';
		controller.setObjects();

		System.assertNotEquals(null, controller.theConfig );
		System.assertNotEquals( null, controller.theConfig.Name );

		// configure the mapping

		controller.theConfig.Use_Queueable__c = false;
		controller.theConfig.Additional_Filter_Clause__c = ' AND CreatedDate != null ';

		// set the right box
		controller.theConfig.Do_Math_Query__c = true;

		controller.theConfig.queryField_parentRelationshipName__c = 'AccountId';
		controller.theConfig.Date_Math_Query_Type__c = 'MAX';
		// set up some bogus fields...
		controller.theConfig.queryField1__c = 'Birthdate';
		controller.theConfig.parentQueryField1__c = 'NumberOfEmployees';
		controller.saveConfig();


		refreshData();

		// fire the rollup...
		//Pass in the API name of the child object, for example 'Contact' and the API name of the parent object, for example 'Account';
		SG_LookupRollupHelper lh = new SG_LookupRollupHelper( 'Contact', 'Account');

		// take care of assigning the correct lists based on the trigger type (Insert vs Update vs Delete vs Undelete)
		lh.setTriggerLists(true, false, contacts, null);

		// do the rollup(s) -- will execute all active rollups for current child/parent configuration
		lh.doRollupSummary();
	}

	/*
	static testMethod void testCheckboxes()
	{
		td = new SG_TDG_LookupRollupSummary();
		refreshData();


		//Pass in the API name of the child object, for example 'Contact' and the API name of the parent object, for example 'Account';
		SG_LookupRollupHelper lh = new SG_LookupRollupHelper( 'Contact', 'Account');

		List<Contact> contacts2 = new List<Contact>();
		for ( Contact c : contacts )
		{
			c.FirstName = 'NEW';
			contacts2.add( c );
		}

		// take care of assigning the correct lists based on the trigger type (Insert vs Update vs Delete vs Undelete)
		lh.setTriggerLists(false, false, contacts2, contacts);


		RollupConfigs__c config = new RollupConfigs__c();
		PageReference theScreen = Page.SG_LRHSetup;
		Test.setCurrentPage(theScreen);
		//System.currentPageReference().getParameters().put('acctId', a.Id);

		ApexPages.StandardController con = new ApexPages.Standardcontroller( config );
		SG_VFC_LRHSetup controller = new SG_VFC_LRHSetup( con );

		// create a new mapping
		controller.doShowCreateSection();
		controller.childObject = 'Contact';
		controller.parentObject = 'Account';
		controller.setObjects();

		System.assertNotEquals(null, controller.theConfig );
		System.assertNotEquals( null, controller.theConfig.Name );

		// configure the mapping
		controller.theConfig.queryField_parentRelationshipName__c = 'AccountId';
		controller.theConfig.Use_Queueable__c = true;
		controller.theConfig.Additional_Filter_Clause__c = ' AND CreatedDate != null ';
		controller.saveConfig();


		refreshData();

		// now lets click some boxes to fire the refresh methods...
		controller.theConfig.Do_Math_Query__c = true;
		controller.theConfig.Do_Date_Query__c = false;
		controller.theConfig.Do_Date_Time_Query__c = false;
		controller.theConfig.Date_Math_Query_Type__c = 'MAX';
		controller.saveConfig();

		refreshData();
		// fire the rollup...
		lh.mappingToUse = controller.theConfig.Name;
		lh.doRollupSummary();

		controller.theConfig.Do_Math_Query__c = false;
		controller.theConfig.Do_Date_Query__c = true;
		controller.theConfig.Do_Date_Time_Query__c = false;
		controller.theConfig.Date_Math_Query_Type__c = 'MAX';
		controller.saveConfig();

		refreshData();
		// fire the rollup...
		lh.mappingToUse = controller.theConfig.Name;
		lh.doRollupSummary();

		controller.theConfig.Do_Math_Query__c = false;
		controller.theConfig.Do_Date_Query__c = false;
		controller.theConfig.Do_Date_Time_Query__c = true;
		controller.theConfig.Date_Math_Query_Type__c = 'MAX';
		controller.saveConfig();

		refreshData();
		// fire the rollup...
		lh.mappingToUse = controller.theConfig.Name;
		lh.doRollupSummary();

	}*/

	public static void refreshData()
	{
		accounts = [SELECT Id, Name FROM Account];
		contacts = [SELECT Id, Name, Email, AccountId FROM Contact ];
		rollupConfigs = [SELECT Id, Name, Child_Object_Name__c, Parent_Object__c, parentRowCount__c, queryField_parentRelationshipName__c, Active__c, Use_Queueable__c
				, queryField1__c, queryField2__c, queryField3__c, queryField4__c, queryField5__c
				, parentQueryField1__c, parentQueryField2__c, parentQueryField3__c, parentQueryField4__c, parentQueryField5__c,
				Config_Notes__c, Additional_Filter_Clause__c, Do_Date_Query__c, Do_Date_Time_Query__c, Do_Math_Query__c, Date_Math_Query_Type__c
				FROM RollupConfigs__c];

	}


}