force-app/main/default/objects/Quality_Control__c/Quality_Control__c.object-meta.xml
<CustomObject>
    <label>Quality Control</label>
    <nameField>
        <displayFormat>QC-{00000000}</displayFormat>
        <label>Quality Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Control</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Control__c/fields/Field_Service_Manager__c.field-meta.xml
<CustomField>
    <fullName>Field_Service_Manager__c</fullName>
    <formula>Work_Order__r.Field_Service_Manager__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Field Service Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quality_Control__c/fields/House_Unit__c.field-meta.xml
<CustomField>
    <fullName>House_Unit__c</fullName>
    <label>House/Unit</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Quality Control</relationshipLabel>
    <relationshipName>Quality_Control</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quality_Control__c/fields/Most_recent_Case_Created__c.field-meta.xml
<CustomField>
    <fullName>Most_recent_Case_Created__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Most recent Case Created</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Quality Control</relationshipLabel>
    <relationshipName>Quality_Control</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Control__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Quality Control</relationshipLabel>
    <relationshipName>Quality_Control</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Control__c/recordTypes/Pre_Walk.recordType-meta.xml
<RecordType>
    <fullName>Pre_Walk</fullName>
    <active>true</active>
    <label>Pre-Walk</label>
</RecordType>

force-app/main/default/classes/ADG_FSLUtilities_Test.cls
/***********************************************************************************
* Name:     	ADG_FSLUtilities_Test
* Author:   	Pushkar
* Main Class:  ADG_FSLUtilities
* ======================================================
* History:
* VER   DATE          INITIALS      DESCRIPTION/FEATURES ADDED
* 1.0   May 18 2021   pushkar       Initial Development for FSL 
*
***********************************************************************************/
@isTest
public class ADG_FSLUtilities_Test {
    
    @TestSetup
    public static void setupData() {
        SG_WorkOrderHelper_Test.createDataForFSL();

        // create/query objects to test
        Account installer = [
                SELECT ID
                FROM Account
                WHERE Name LIKE 'Installer%'
                LIMIT 1
        ];

        Asset anAsset = [
                SELECT ID, Field_Service_Manager__c, AccountID
                FROM Asset
                WHERE Name = '1313 Mockingbird'
                LIMIT 1
        ];

        SG_ServiceAppointment.recordIdsAlreadyProcessedSet = new Set<ID>();

        WorkOrder wo = new WorkOrder();
        wo.AssetId = anAsset.ID;
        wo.Installer_Account__c = installer.ID;
        wo.Job_Type__c = 'QC Pre-Walk';
        wo.Start_Day__c = Date.today().addDays( 1 );
        wo.Job_End_Day__c = Date.today().addDays( 3 );

        system.debug( 'inserting test WO= ' + wo );
        insert wo;
        
        Quality_Control__c qc = [
                SELECT ID, House_Unit__c, Work_Order__c, Most_Recent_Case_Created__c
                FROM Quality_Control__c
                WHERE House_Unit__r.Name = '1313 Mockingbird'
                AND Work_Order__r.Job_Type__c = 'QC Pre-Walk'
                LIMIT 1
        ];
       	String originalTitle = 'Test';
		String docPath = 'Test.jpg';
        
        // add a file...
		ContentVersion cv = new ContentVersion(
				Title = 'Test.jpg',
				PathOnClient = docPath,
				VersionData = blob.valueof('Test Content Data'),
				IsMajorVersion = true);
		insert cv;
        
        ContentDocument docs = [SELECT Id, Title, FileType, FileExtension, LatestPublishedVersionId FROM ContentDocument];
             
        ContentDocumentLink contentlink=new ContentDocumentLink();
		contentlink.LinkedEntityId= qc.Id;
		contentlink.ShareType= 'I';
		contentlink.ContentDocumentId= docs.Id ;
		contentlink.Visibility = 'AllUsers';
		insert contentlink;
    }
    
    static testMethod void renameFiles_test(){
        Test.startTest();
        Quality_Control__c qcTest = [
                SELECT ID, House_Unit__c, Work_Order__c, Most_Recent_Case_Created__c
                FROM Quality_Control__c
                WHERE House_Unit__r.Name = '1313 Mockingbird'
                AND Work_Order__r.Job_Type__c = 'QC Pre-Walk'
                LIMIT 1
        ];
        ContentDocument docTest = [SELECT Id, Title, FileType, FileExtension, LatestPublishedVersionId FROM ContentDocument LIMIT 1];
        
        system.debug('@QCId' + qcTest.Id);
        ADG_FSLUtilities.FlowInputs fslinp = new ADG_FSLUtilities.FlowInputs();
        fslinp.fileNames = docTest.Title;
        fslinp.prefix = 'Pre_Walk';
        fslinp.recId = qcTest.Id;
        List<ADG_FSLUtilities.FlowInputs> listinp = new List<ADG_FSLUtilities.FlowInputs>();
        listinp.add(fslinp);
        ADG_FSLUtilities.renameFiles(listinp);
        Test.stopTest();
    }
}