force-app/main/default/objects/Community__c/Community__c.object-meta.xml
<CustomObject>
    <label>Community</label>
    <nameField>
        <label>Community</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Community__c/fields/Field_Service_Manager__c.field-meta.xml
<CustomField>
    <fullName>Field_Service_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Must be Service Resource</inlineHelpText>
    <label>Field Service Manager</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipName>Communities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community__c/recordTypes/Exception.recordType-meta.xml
<RecordType>
    <fullName>Exception</fullName>
    <active>true</active>
    <label>Exception</label>
</RecordType>

force-app/main/default/classes/ADG_CommunitiesHelper.cls
/***********************************************************************************
 * Name:     	ADG_CommunitiesHelper
 * Author:   	Pushkar
 * Test Class:	ADG_CommunitiesHelper_Test
 * ======================================================
 * History:
 * VER   DATE          INITIALS      DESCRIPTION/FEATURES ADDED
 * 1.0   Dec-29-2020   pushkar       Initial Development to be invoked from Trigger
 *
 ***********************************************************************************/

public with sharing class ADG_CommunitiesHelper {
  public static void invokeAfterUpdate(
    System.TriggerOperation operationType,
    List<Community__c> updList,
    Map<Id, Community__c> oldMap
  ) {
    if (operationType != TriggerOperation.AFTER_UPDATE) {
      //validate that this is only being executed from After Update trigger.
      return;
    }

    Set<Id> updFSMList = new Set<Id>();
    for (Community__c c : updList) {
      //Loop records to create List if FSM Changed
      if (
        c.Field_Service_Manager__c != oldMap.get(c.Id).Field_Service_Manager__c
      ) {
        updFSMList.add(c.Id);
      }
    }

    if (updFSMList.size() > 0) {
      List<Asset> assetIds = [
        SELECT
          ID,
          Community__r.Field_Service_Manager__c,
          Field_Service_Manager__c
        FROM ASSET
        WHERE
          Community__r.ID IN :updFSMList];
      if (assetIds.size() > 0) {
        List<Asset> assetUpdate = new List<Asset>();
        for (Asset a : assetIds) {
          a.Field_Service_Manager__c = a.Community__r.Field_Service_Manager__c;
          assetUpdate.add(a);
        }
        //update assetUpdate;
        try {
          Database.SaveResult[] res = Database.update(assetUpdate, false);
        } catch (Exception e) {
          system.debug('@@@Exception Type: ' + e.getTypeName());
          system.debug('@@@Exception Line: ' + e.getLineNumber());
          system.debug('@@@Exception Msg: ' + e.getMessage());
        }
      }
    }
  }
}