force-app/main/default/objects/Community__c/Community__c.object-meta.xml
<CustomObject>
    <label>Community</label>
    <nameField>
        <label>Community</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Team__c/Community_Team__c.object-meta.xml
<CustomObject>
    <description>Team based sharing for Community with FSMs</description>
    <label>Community Team</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Community Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Team__c/fields/Community__c.field-meta.xml
<CustomField>
    <fullName>Community__c</fullName>
    <label>Community</label>
    <referenceTo>Community__c</referenceTo>
    <relationshipLabel>Community Teams</relationshipLabel>
    <relationshipName>Community_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Community_Team__c/fields/Field_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Field_User_Id__c</fullName>
    <description>Fetch the user record associated with FSM</description>
    <formula>FSM__r.RelatedRecordId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Field User Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HouseTeamMember.cls
public without sharing class HouseTeamMember {
    
    public static void createShares(Map<Id, Community__c> communityHouseTeamMap){
        List<AssetShare> sharesToInsert = new List<AssetShare>(); //RowCause, AssetId, UserOrGroupId, AssetAccessLevel
        Set<String> insertedParentAndUser = new Set<String>();
        for (String key : communityHouseTeamMap.keySet()){
            Community__c communityRec = communityHouseTeamMap.get(key);
            for (Asset house: communityRec.House_Units__r){
                for (Community_Team__c ct : communityRec.Community_Teams__r){
                    String parentAndUser = String.valueOf(house.Id) + String.valueOf(ct.Field_User_Id__c);
                    if (insertedParentAndUser.contains(parentAndUser)) continue;
                    if (house.OwnerId == ct.Field_User_Id__c) continue;
                    sharesToInsert.add(new AssetShare(
                        //ParentId, UserOrGroupId, AccessLevel, RowCause
                        AssetId = house.Id, UserOrGroupId = ct.Field_User_Id__c, AssetAccessLevel = 'Edit', RowCause = 'Manual'));
                    insertedParentAndUser.add(parentAndUser); 
                } 
            }
        }
        if (! sharesToInsert.IsEmpty()){
            insert sharesToInsert;
        }
    }
    
    public static void shareOnFSMUpd(Map<Id, Community__c> communityTeamMap){
        Set<Id> communitySet = new Set<Id>();
        communitySet = communityTeamMap.keySet();
        List<AssetShare> sharesToDelete = new List<AssetShare>([Select Id  from AssetShare where Asset.Community__c  IN:communitySet  AND RowCause = 'Manual']);
        if (! sharesToDelete.IsEmpty()){
            delete sharesToDelete;
        }
        createShares(communityTeamMap);
    }
}