force-app/main/default/objects/Community__c/Community__c.object-meta.xml
<CustomObject>
    <label>Community</label>
    <nameField>
        <label>Community</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Community__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ADG_Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community__c/fields/Field_Service_Manager__c.field-meta.xml
<CustomField>
    <fullName>Field_Service_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Must be Service Resource</inlineHelpText>
    <label>Field Service Manager</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipName>Communities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Team__c/Community_Team__c.object-meta.xml
<CustomObject>
    <description>Team based sharing for Community with FSMs</description>
    <label>Community Team</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Community Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Team__c/fields/Community__c.field-meta.xml
<CustomField>
    <fullName>Community__c</fullName>
    <label>Community</label>
    <referenceTo>Community__c</referenceTo>
    <relationshipLabel>Community Teams</relationshipLabel>
    <relationshipName>Community_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Community_Team__c/fields/Field_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Field_User_Id__c</fullName>
    <description>Fetch the user record associated with FSM</description>
    <formula>FSM__r.RelatedRecordId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Field User Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Team__c/fields/FSM__c.field-meta.xml
<CustomField>
    <fullName>FSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FSM</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Community Teams</relationshipLabel>
    <relationshipName>Community_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Team__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TILE</fullName>
            </value>
            <value>
                <fullName>CABINET</fullName>
            </value>
            <value>
                <fullName>CARPET</fullName>
            </value>
            <value>
                <fullName>COUNTERTOPS</fullName>
            </value>
            <value>
                <fullName>LAMINATE</fullName>
            </value>
            <value>
                <fullName>LVP</fullName>
            </value>
            <value>
                <fullName>SPECIALTY</fullName>
            </value>
            <value>
                <fullName>VINYL</fullName>
            </value>
            <value>
                <fullName>WOOD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ADG_Entity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Arlun</fullName>
    </customValue>
    <customValue>
        <fullName>AWC</fullName>
    </customValue>
    <customValue>
        <fullName>BWF</fullName>
    </customValue>
    <customValue>
        <fullName>Decor</fullName>
    </customValue>
    <customValue>
        <fullName>Dixie</fullName>
    </customValue>
    <customValue>
        <fullName>Floors</fullName>
    </customValue>
    <customValue>
        <fullName>Heritage</fullName>
    </customValue>
    <customValue>
        <fullName>Images</fullName>
    </customValue>
    <customValue>
        <fullName>Just Floors</fullName>
    </customValue>
    <customValue>
        <fullName>Kermans</fullName>
    </customValue>
    <customValue>
        <fullName>Malibu</fullName>
    </customValue>
    <customValue>
        <fullName>Markraft</fullName>
    </customValue>
    <customValue>
        <fullName>McDade</fullName>
    </customValue>
    <customValue>
        <fullName>Metro</fullName>
    </customValue>
    <customValue>
        <fullName>Nonn&apos;s</fullName>
    </customValue>
    <customValue>
        <fullName>NuWood</fullName>
    </customValue>
    <customValue>
        <fullName>Value Plus</fullName>
    </customValue>
    <customValue>
        <fullName>Vintage</fullName>
    </customValue>
    <customValue>
        <fullName>WCCV</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <masterLabel>ADG Entity</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WorkOrderSyncCommunityTeamsFSM.cls
public without sharing class WorkOrderSyncCommunityTeamsFSM {
    
    public static void syncCommunityTeamFSMOnWO(List<WorkOrder> workOrdersList){
        String enabledEntities = System.Label.Teams_Entities;
        Map<Id, Community__c> communityTeams = new Map<Id, Community__c>();
        communityTeams = getCommunityTeams(workOrdersList);
        for (WorkOrder wo : workOrdersList){
            Community__c communityRec = communityTeams.get(wo.Community__c);
            if (communityRec.Entity__c != null){
                if (enabledEntities.contains(communityRec.Entity__c) || Test.isRunningTest()){
                    for (Community_Team__c ct : communityRec.Community_Teams__r){
                        if (ct.Job_Type__c != null && wo.Job_Type__c != null){
                            if (wo.Job_Type__c.contains(ct.Job_Type__c.toUpperCase())){
                                wo.Field_Service_Manager__c = ct.FSM__c;
                                wo.OwnerId = ct.Field_User_Id__c;
                                break;
                            }
                        }
                    }
                }
            }
        }
    }
    
    public static Map<Id, Community__c> getCommunityTeams(List<WorkOrder> woList){
        Set<Id> communityId = new Set<ID>();
        Map<Id, Community__c> communityTeamMap = new Map<Id, Community__c>();
        for (WorkOrder order: woList){
            if (order.Community__c != null){
                communityId.add(order.Community__c);
            }
        }
        if (! communityId.isEmpty()){
            communityTeamMap = new Map<Id, Community__c> ([Select Id, Entity__c, (Select Field_User_Id__c, FSM__c, Job_Type__c from Community_Teams__r) from Community__c where Id IN: communityId]); 
        }
        return communityTeamMap;
    }
    
}