force-app/main/default/objects/Community__c/Community__c.object-meta.xml
<CustomObject>
    <label>Community</label>
    <nameField>
        <label>Community</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Community__c/fields/Builder__c.field-meta.xml
<CustomField>
    <fullName>Builder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Builder</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Communities</relationshipLabel>
    <relationshipName>Sub_Divisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community__c/fields/Field_Service_Manager__c.field-meta.xml
<CustomField>
    <fullName>Field_Service_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Must be Service Resource</inlineHelpText>
    <label>Field Service Manager</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipName>Communities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Team__c/Community_Team__c.object-meta.xml
<CustomObject>
    <description>Team based sharing for Community with FSMs</description>
    <label>Community Team</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Community Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Team__c/fields/Community__c.field-meta.xml
<CustomField>
    <fullName>Community__c</fullName>
    <label>Community</label>
    <referenceTo>Community__c</referenceTo>
    <relationshipLabel>Community Teams</relationshipLabel>
    <relationshipName>Community_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Community_Team__c/fields/FSM__c.field-meta.xml
<CustomField>
    <fullName>FSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FSM</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Community Teams</relationshipLabel>
    <relationshipName>Community_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Team__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TILE</fullName>
            </value>
            <value>
                <fullName>CABINET</fullName>
            </value>
            <value>
                <fullName>CARPET</fullName>
            </value>
            <value>
                <fullName>COUNTERTOPS</fullName>
            </value>
            <value>
                <fullName>LAMINATE</fullName>
            </value>
            <value>
                <fullName>LVP</fullName>
            </value>
            <value>
                <fullName>SPECIALTY</fullName>
            </value>
            <value>
                <fullName>VINYL</fullName>
            </value>
            <value>
                <fullName>WOOD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/massCommunityTeams.cls
public without sharing class massCommunityTeams {
    
    private static Map<string,Community__c> communityWithBuilderMap = new Map<string,Community__c>();
    private static Map<string,Id> serviceResourceMap = new Map<string,Id>();
    private static Set<string> communitySet = new Set<string>();
    private static Set<string> builderSet = new Set<string>();
    private static Set<string> FSMSet = new Set<string>();
    private static List<Community__c> commUpdList = new List <Community__c>(); 
    private static List<Community_Team__c> commTeamList = new List<Community_Team__c>();
    
    @AuraEnabled
    public static void uploadCommunityMembers(String inputCasesJSON){
        List<csvRecs> recsList = (List<csvRecs>) System.JSON.deserialize(inputCasesJSON, List<csvRecs>.class);
        List<csvRecs> recsToProcessList = new List<csvRecs>();
        for (csvRecs rec : recsList){
            if (String.isNotEmpty(rec.BuilderName) && String.isNotEmpty(rec.CommunityName) && 
                (String.isNotEmpty(rec.CommunityOwnerEmail) ||
                 (String.isNotEmpty(rec.CommunityTeamMemberEmail) && String.isNotEmpty(rec.JobType)))){
                     String strBuilderName = rec.BuilderName.replaceAll('"', '');
                     String strCommunityName = rec.CommunityName.replaceAll('"', '');
                     rec.BuilderName = strBuilderName;
                     rec.CommunityName = strCommunityName;
                     recsToProcessList.add(rec); //Cleaned List
                     communitySet.add(strCommunityName);
                     builderSet.add(strBuilderName);
                     if (String.isNotEmpty(rec.CommunityOwnerEmail)){
                         FSMSet.add(rec.CommunityOwnerEmail); 
                     }
                     if (String.isNotEmpty(rec.CommunityTeamMemberEmail)){
                         FSMSet.add(rec.CommunityTeamMemberEmail); 
                     }
                 }
        }
        if (!recsToProcessList.isEmpty()){
            String commIdString;
            String commBuilder;
            Id FSMId; //System.assert(!String.isEmpty(whitespace));
            system.debug('@@@ Before Map Builder' + JSON.serialize(builderSet));
            system.debug('@@@ Before Map FSM' + JSON.serialize(FSMSet));
            communityMap();
            FSMMap();
            system.debug('@@@ After Map Builder ' + JSON.serialize(communityWithBuilderMap));
            system.debug('@@@ After Map FSM ' + JSON.serialize(serviceResourceMap));
            if (!(communityWithBuilderMap.isEmpty() && serviceResourceMap.isEmpty())){
                for (csvRecs rec : recsToProcessList){
                    commBuilder = null;
                    FSMId = null;
                    commBuilder = rec.BuilderName.toLowerCase() + '-' + rec.CommunityName.toLowerCase();
                    Community__c commRec = communityWithBuilderMap.get(commBuilder);
                    if (commRec != null){
                        if (commRec.Id != null){
                            if (rec.CommunityOwnerEmail != null){
                                if (String.IsEmpty(commIdString)){
                                    FSMId = serviceResourceMap.get(rec.CommunityOwnerEmail.toLowerCase());                            
                                }
                                else {
                                    if (!(commIdString.contains(commRec.Id))){
                                        FSMId = serviceResourceMap.get(rec.CommunityOwnerEmail.toLowerCase());
                                    }
                                }
                            }
                            if (rec.CommunityOwnerEmail != commRec.Field_Service_Manager__r.RelatedRecord.Email && FSMId != null){
                                commRec.Field_Service_Manager__c = FSMId;
                                if (commIdString == null){
                                    commIdString = commRec.Id;
                                } else {
                                    commIdString += ',' + commRec.Id;   
                                }
                                commUpdList.add(commRec);
                            }
                            if (String.isNotEmpty(rec.CommunityTeamMemberEmail) && String.isNotEmpty(rec.JobType)){
                                FSMId = serviceResourceMap.get(rec.CommunityTeamMemberEmail.toLowerCase());
                                if (FSMId != null){
                                    Community_Team__c ctm = new Community_Team__c(Community__c = commRec.Id, FSM__c = FSMId, Job_Type__c = rec.JobType);
                                    commTeamList.add(ctm);
                                }
                            }
                        }
                    }
                }
            }
            system.debug('@@@ commUpdList  ' + JSON.serialize(commUpdList));
            system.debug('@@@ commTeamList ' + JSON.serialize(commTeamList));
            if (commUpdList.size() > 0){
                Database.SaveResult[] saveResultList = Database.update(commUpdList, false);
            }
            if (commTeamList.size() > 0){
                Database.SaveResult[] saveResultList1 = Database.insert(commTeamList, false);
            }
        }
    }
    
    private static void  communityMap(){
        for (Community__c c : [SELECT Id, Builder__r.Name, Name, Field_Service_Manager__r.RelatedRecord.Email, Field_Service_Manager__c 
                               FROM Community__c where  Name IN: communitySet  AND Builder__r.Name IN: builderSet]){
                                   communityWithBuilderMap.put(c.Builder__r.Name.toLowerCase() + '-' + c.Name.toLowerCase(), c); 
                               }
    }
    
    private static void FSMMap(){
        for (ServiceResource s: [SELECT Id,RelatedRecord.Email  from ServiceResource where RelatedRecord.Email IN: FSMSet]){
            serviceResourceMap.put(s.RelatedRecord.Email.toLowerCase(), s.Id);
        }
    }
    
    public class csvRecs {
        public String BuilderName;
        public String CommunityName;
        public String CommunityOwnerEmail;
        public String CommunityTeamMemberEmail;
        public String JobType;
    }
    
}