force-app/main/default/objects/Community__c/Community__c.object-meta.xml
<CustomObject>
    <label>Community</label>
    <nameField>
        <label>Community</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Community__c/fields/Builder__c.field-meta.xml
<CustomField>
    <fullName>Builder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Builder</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Communities</relationshipLabel>
    <relationshipName>Sub_Divisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community__c/fields/Field_Service_Manager__c.field-meta.xml
<CustomField>
    <fullName>Field_Service_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Must be Service Resource</inlineHelpText>
    <label>Field Service Manager</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipName>Communities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SG_Asset_LU_Test.cls
@IsTest
public class SG_Asset_LU_Test 
{
    private static SG_TestDataGenerator td;
    private static List<Account> accounts;
    private static List<Community__c> comms;
    private static List<Asset> houses;
    private static List<ServiceResource> servResource;
    
    
    public static Boolean isTest = false;

    
    @testSetup static void setupTestData()
    {
        isTest = true;
        ADG_TestSetup.Setup();
        //td = new SG_TestDataGenerator();
        //accounts = td.getAccounts(true);
    }
    
    static testMethod void testBehavior()
    {
        // the LU Helper has it's own test class. We just need to fire the trigger for test coverage
        refreshData();
        /*
        System.debug('---> accounts: ' + accounts );
        Account a = accounts[0];
        Community__c com = new Community__c();
        com.Name = 'Test';
        com.Builder__c = a.Id;
        insert com;
        
        refreshData();
        com = comms[0];
        ServiceResource serv = servResource[0];
        
        Id houseRtId = Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get('House').getRecordTypeId();
        
        Asset ast = new Asset();
        ast.Community__c = com.Id;
        ast.Name = 'Test Asset';
        ast.RecordTypeId = houseRtId;
        ast.Lot_Block__c = 'Lot';
        ast.AccountId = a.Id;
        ast.Field_Service_Manager__c = serv.Id;
        insert ast;
		*/
        ServiceResource serv = servResource[0];
        Asset ast = houses[0];
        isTest = true;
        update ast;

        // test the activator...
        isTest = false;
        serv = servResource[1];
        ast.Field_Service_Manager__c = serv.Id;
        update ast;
        
    }

    public static void refreshData()
    {
        accounts = [SELECT Id, Name FROM Account];
        comms = [SELECT Id, Name FROM Community__c];
        houses = [SELECT Id, Field_Service_Manager__c FROM Asset];
        servResource = [SELECT ID from ServiceResource];
    }
}