force-app/main/default/objects/Community__c/Community__c.object-meta.xml
<CustomObject>
    <label>Community</label>
    <nameField>
        <label>Community</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Community__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ADG_Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Control__c/Quality_Control__c.object-meta.xml
<CustomObject>
    <label>Quality Control</label>
    <nameField>
        <displayFormat>QC-{00000000}</displayFormat>
        <label>Quality Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Control</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Control__c/fields/Community__c.field-meta.xml
<CustomField>
    <fullName>Community__c</fullName>
    <formula>House_Unit__r.Community__r.Name</formula>
    <label>Community</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quality_Control__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <formula>TEXT(Work_Order__r.Account.Entity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quality_Control__c/fields/House_Unit__c.field-meta.xml
<CustomField>
    <fullName>House_Unit__c</fullName>
    <label>House/Unit</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Quality Control</relationshipLabel>
    <relationshipName>Quality_Control</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quality_Control__c/fields/QCType__c.field-meta.xml
<CustomField>
    <fullName>QCType__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QCType</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quality_Control__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Please select a value&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ADG_Entity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Arlun</fullName>
    </customValue>
    <customValue>
        <fullName>AWC</fullName>
    </customValue>
    <customValue>
        <fullName>BWF</fullName>
    </customValue>
    <customValue>
        <fullName>Decor</fullName>
    </customValue>
    <customValue>
        <fullName>Dixie</fullName>
    </customValue>
    <customValue>
        <fullName>Floors</fullName>
    </customValue>
    <customValue>
        <fullName>Heritage</fullName>
    </customValue>
    <customValue>
        <fullName>Images</fullName>
    </customValue>
    <customValue>
        <fullName>Just Floors</fullName>
    </customValue>
    <customValue>
        <fullName>Kermans</fullName>
    </customValue>
    <customValue>
        <fullName>Malibu</fullName>
    </customValue>
    <customValue>
        <fullName>Markraft</fullName>
    </customValue>
    <customValue>
        <fullName>McDade</fullName>
    </customValue>
    <customValue>
        <fullName>Metro</fullName>
    </customValue>
    <customValue>
        <fullName>Nonn&apos;s</fullName>
    </customValue>
    <customValue>
        <fullName>NuWood</fullName>
    </customValue>
    <customValue>
        <fullName>Value Plus</fullName>
    </customValue>
    <customValue>
        <fullName>Vintage</fullName>
    </customValue>
    <customValue>
        <fullName>WCCV</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <masterLabel>ADG Entity</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ADG_ManageQC.cls
public class ADG_ManageQC {
    @AuraEnabled
    public static String submitBatch(Date qcCreatedDate, String strEntity, String strFieldName, String strFieldLabel, String strButtonClk){
        List<Community__c> commList = [SELECT Id FROM Community__c where Entity__c =: strEntity WITH SECURITY_ENFORCED];
        if (commList.size()> 0){
            List<Community__c> commUpdList = new List<Community__c>();
            for (Community__c c: commList){
                if (strButtonClk == 'disable'){
                    //fl.put(fieldName,12.0);
                    c.put(strFieldName, 'No');  
                } else if (strButtonClk == 'enable'){
                    c.put(strFieldName, 'Yes');
                }
                commUpdList.add(c);
            }
            //system.debug('@commList' + Json.serialize(commList));
            //system.debug('@commUpdList' + Json.serialize(commUpdList)); 
            update commUpdList;
            
            if (strButtonClk == 'disable' && qcCreatedDate != null){ //Delete QCs
                List<Quality_Control__c> qcList = [SELECT Id FROM Quality_Control__c WHERE Status__c != 'Completed' 
                                                   AND QCType__c =: strFieldLabel
                                                   AND House_Unit__r.Community__r.Entity__c =: strEntity
                                                   AND CreatedDate <= :qcCreatedDate
                                                   WITH SECURITY_ENFORCED];
                //system.debug('ListOfQCs' + Json.serialize(qcList)); 
                if (qcList.size() > 0){
                    delete qcList;
                }
            }
        }
        return ('SUCCESS');
    } 
}