force-app/main/default/objects/Community__c/Community__c.object-meta.xml
<CustomObject>
    <label>Community</label>
    <nameField>
        <label>Community</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Team__c/Community_Team__c.object-meta.xml
<CustomObject>
    <description>Team based sharing for Community with FSMs</description>
    <label>Community Team</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Community Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Team__c/fields/Community__c.field-meta.xml
<CustomField>
    <fullName>Community__c</fullName>
    <label>Community</label>
    <referenceTo>Community__c</referenceTo>
    <relationshipLabel>Community Teams</relationshipLabel>
    <relationshipName>Community_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Community_Team__c/fields/Community_Entity__c.field-meta.xml
<CustomField>
    <fullName>Community_Entity__c</fullName>
    <formula>TEXT(Community__r.Entity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Community Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Team__c/fields/Field_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Field_User_Id__c</fullName>
    <description>Fetch the user record associated with FSM</description>
    <formula>FSM__r.RelatedRecordId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Field User Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Team__c/fields/FSM__c.field-meta.xml
<CustomField>
    <fullName>FSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FSM</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Community Teams</relationshipLabel>
    <relationshipName>Community_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Team__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TILE</fullName>
            </value>
            <value>
                <fullName>CABINET</fullName>
            </value>
            <value>
                <fullName>CARPET</fullName>
            </value>
            <value>
                <fullName>COUNTERTOPS</fullName>
            </value>
            <value>
                <fullName>LAMINATE</fullName>
            </value>
            <value>
                <fullName>LVP</fullName>
            </value>
            <value>
                <fullName>SPECIALTY</fullName>
            </value>
            <value>
                <fullName>VINYL</fullName>
            </value>
            <value>
                <fullName>WOOD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Team__c/fields/UniqueJobType__c.field-meta.xml
<CustomField>
    <fullName>UniqueJobType__c</fullName>
    <label>UniqueJobFSM</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CommunityTeamMemberTriggerHandlerTest.cls
@isTest
public without sharing class CommunityTeamMemberTriggerHandlerTest {
    
    @TestSetUP
    public static void setupData() {
        ADG_TestSetup.Setup(); //SetUp Accounts and Workorders
    }
    
    @isTest
    static void testCreateShares() {
        Test.startTest();
        List<Community_Team__c> teamMembers = [Select Community__c, Community_Entity__c, Field_User_Id__c, FSM__c, Job_Type__c , 
                                               UniqueJobType__c from Community_Team__c LIMIT 5];
        CommunityTeamMemberTriggerHandler.createShares(teamMembers);
        Test.stopTest();
    }
    
    @isTest
    static void testAddDefaults() {
        List<Community_Team__c> teamMembers = [Select Community__c, Community_Entity__c, Field_User_Id__c, FSM__c, Job_Type__c , 
                                               UniqueJobType__c from Community_Team__c LIMIT 5];
        Test.startTest();
        CommunityTeamMemberTriggerHandler.addDefaults(teamMembers);
        Test.stopTest();
    }

    @isTest
    static void testUpdateShares() {
        List<Community_Team__c> teamMembers = [Select Community__c, Community_Entity__c, Field_User_Id__c, FSM__c, Job_Type__c , 
                                               UniqueJobType__c from Community_Team__c WHERE FSM__r.Name = 'Test FieldServiceManager2' LIMIT 1];
        List<ServiceResource> fsmList = [SELECT Id From ServiceResource where Name = 'Test FieldServiceManager3'];
        Test.startTest();
        system.debug('@@@1 ' + teamMembers[0].FSM__c);
        system.debug('@@@2 ' + fsmList[0].Id);
        for (Community_Team__c tm : teamMembers){
            tm.FSM__c = fsmList[0].Id;
            update tm;
        }
        Test.stopTest();        
    }
    
    /*@isTest
    static void testShareOnFSMUpd(){
        
    }*/
}