force-app/main/default/objects/Community__c/Community__c.object-meta.xml
<CustomObject>
    <label>Community</label>
    <nameField>
        <label>Community</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Team__c/Community_Team__c.object-meta.xml
<CustomObject>
    <description>Team based sharing for Community with FSMs</description>
    <label>Community Team</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Community Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Team__c/fields/Community__c.field-meta.xml
<CustomField>
    <fullName>Community__c</fullName>
    <label>Community</label>
    <referenceTo>Community__c</referenceTo>
    <relationshipLabel>Community Teams</relationshipLabel>
    <relationshipName>Community_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Community_Team__c/fields/Field_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Field_User_Id__c</fullName>
    <description>Fetch the user record associated with FSM</description>
    <formula>FSM__r.RelatedRecordId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Field User Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Team__c/fields/FSM__c.field-meta.xml
<CustomField>
    <fullName>FSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FSM</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Community Teams</relationshipLabel>
    <relationshipName>Community_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Team__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TILE</fullName>
            </value>
            <value>
                <fullName>CABINET</fullName>
            </value>
            <value>
                <fullName>CARPET</fullName>
            </value>
            <value>
                <fullName>COUNTERTOPS</fullName>
            </value>
            <value>
                <fullName>LAMINATE</fullName>
            </value>
            <value>
                <fullName>LVP</fullName>
            </value>
            <value>
                <fullName>SPECIALTY</fullName>
            </value>
            <value>
                <fullName>VINYL</fullName>
            </value>
            <value>
                <fullName>WOOD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HouseTeamMember_Test.cls
/***********************************************************************************
* Name:     	HouseTeamMember_Test
* Author:   	Pushkar
* Main Class:	HouseTeamMember
* ======================================================
* History:
* VER   DATE          INITIALS      DESCRIPTION/FEATURES ADDED
* 1.0   Aug-01-2023   pushkar       Initial Development to be test
*
***********************************************************************************/
@isTest
public class HouseTeamMember_Test {
    
    static testMethod void HouseTeamMembershareOnFSMUpd(){
        Test.startTest();
        ADG_TestSetup.Setup(); //SetUp Accounts and Workorders
        Map<Id, Community__c> communityHouseMap = new Map<Id, Community__c> ([Select Id, (Select Id, Status, OwnerId from House_Units__r), (Select Field_User_Id__c, FSM__c, Job_Type__c from Community_Teams__r) from Community__c]); 
        system.debug('@@@@' + JSON.serialize(communityHouseMap));
        HouseTeamMember.shareOnFSMUpd(communityHouseMap);
        Test.stopTest();
    }
}