force-app/main/default/objects/Custom_Apex_Error_Handler__c/Custom_Apex_Error_Handler__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Custom Apex Error Handler</label>
</CustomObject>

force-app/main/default/objects/Custom_Apex_Error_Handler__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>You can send emails to the current user by specifying the Name of the Custom Setting to start with &quot;CurrentUser&quot; (no quotes). Example: CurrentUser_ForSuchAndSuch.</description>
    <inlineHelpText>You can send emails to the current user by specifying the Name of the Custom Setting to start with &quot;CurrentUser&quot; (no quotes). Example: CurrentUser_ForSuchAndSuch.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Custom_Apex_Error_Handler__c/fields/Log_Exceptions__c.field-meta.xml
<CustomField>
    <fullName>Log_Exceptions__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this checkbox to log ALL, Class Specific or Exception Specific Exceptions</description>
    <inlineHelpText>Check this checkbox to log ALL, Class Specific or Exception Specific Exceptions</inlineHelpText>
    <label>Log Exceptions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Apex_Error_Handler__c/fields/Single_Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Single_Apex_Class__c</fullName>
    <inlineHelpText>List the name of a single apex class from which you want to get emails upon errors - if and only if the apex class was coded to leverage these settings. If left blank, person will get every email possible.</inlineHelpText>
    <label>Single Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Apex_Error_Handler__c/fields/Single_Exception__c.field-meta.xml
<CustomField>
    <fullName>Single_Exception__c</fullName>
    <label>Single Exception</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SG_ErrorHelper_Test.cls
@IsTest
public with sharing class SG_ErrorHelper_Test {
        
    static testMethod void test_notifyOnErrorCurrentUser() {        
        Custom_Apex_Error_Handler__c setting = new Custom_Apex_Error_Handler__c();
        setting.Name = 'CurrentUser_CustomSettingNameTest';
        setting.Single_Apex_Class__c = 'testClasstest1234';
        setting.Log_Exceptions__c = true;
        insert setting;
        
        SG_ErrorHelper.notifyOnError(setting.Single_Apex_Class__c,'ExceptionName','subject','errorbody');
    }

    static testMethod void test_notifyOnErrorWithUserIds() {        
        Custom_Apex_Error_Handler__c setting = new Custom_Apex_Error_Handler__c();
        setting.Name = 'CustomSettingNameTest';
        setting.Email__c = 'testOne@TesterNoVoidWork.net';
        setting.Single_Apex_Class__c = 'testClasstest1234';
        setting.Log_Exceptions__c = true;
        insert setting;
        
        SG_TestDataGenerator data = new SG_TestDataGenerator();
        User u = data.getUsers(null)[0];
        Set<Id> userIds = new Set<Id>();
        System.assertNotEquals(null,u.Id);
        userIds.add(u.Id);
        SG_ErrorHelper.notifyOnError(setting.Single_Apex_Class__c,'exception','subject','errorbody',userIds);     
    }

    static testMethod void test_notifyOnError() {       
        Custom_Apex_Error_Handler__c setting = new Custom_Apex_Error_Handler__c();
        setting.Name = 'CustomSettingNameTest';
        setting.Email__c = 'testOne@TesterNoVoidWork.net';
        setting.Single_Apex_Class__c = 'testClasstest1234';
        setting.Single_Exception__c = 'exception';
        setting.Log_Exceptions__c = true;
        insert setting;
        
        SG_ErrorHelper.notifyOnError(setting.Single_Apex_Class__c,setting.Single_Exception__c,'subject','errorbody');
    }

/*    
    static testMethod void test_notifyOnErrorSimple() {       
        Custom_Apex_Error_Handler__c setting = new Custom_Apex_Error_Handler__c();
        setting.Name = 'CustomSettingNameTest';
        setting.Email__c = 'testOne@TesterNoVoidWork.net';
        setting.Single_Apex_Class__c = 'testClasstest1234';
        setting.Single_Exception__c = 'exception';
        insert setting;
        
        SG_ErrorHelper.notifyOnError(setting.Single_Apex_Class__c,setting.Single_Exception__c,'errorbody');
    }
*/
   
    static testMethod void test_notifyOnErrorException() {       
        Custom_Apex_Error_Handler__c setting = new Custom_Apex_Error_Handler__c();
        setting.Name = 'CustomSettingNameTest';
        setting.Email__c = 'testOne@TesterNoVoidWork.net';
        setting.Single_Apex_Class__c = 'testClasstest1234';
        setting.Single_Exception__c = 'exception';
        setting.Log_Exceptions__c = true;
        insert setting;
        
        SG_ErrorHelper.notifyOnError(setting.Single_Apex_Class__c,setting.Single_Exception__c,new SG_DisplayUtils.DisplayUtilsException('test'));
    }
    
    static testMethod void test_notifyOnErrorFALSE() {       
        Custom_Apex_Error_Handler__c setting = new Custom_Apex_Error_Handler__c();
        setting.Name = 'CustomSettingNameTest';
        setting.Email__c = 'testOne@TesterNoVoidWork.net';
        setting.Single_Apex_Class__c = '';
        setting.Single_Exception__c = 'exception';
        setting.Log_Exceptions__c = true;
        insert setting;
        
        SG_ErrorHelper.notifyOnError('class','exception','subject','errorbody');
    }
    
    static testMethod void test_notifyOnError_HighVolume() {
        Custom_Apex_Error_Handler__c setting = new Custom_Apex_Error_Handler__c();
        setting.Name = 'CustomSettingNameTest';
        setting.Email__c = 'testVolume@TesterNoVoidWork.net';
        setting.Single_Apex_Class__c = 'testClasstest1234';
        setting.Log_Exceptions__c = true;
        insert setting;
                
        for(Integer i = 0; i < Limits.getLimitEmailInvocations() + 2; i++) {
            SG_ErrorHelper.notifyOnError(setting.Single_Apex_Class__c,'exp','subject','errorbody');
        }
    } 
    
    static testMethod void test_doLogEmail() {       
        Custom_Apex_Error_Handler__c setting = new Custom_Apex_Error_Handler__c();
        setting.Name = 'CustomSettingNameTest';
        setting.Email__c = 'test@testernovoidwork.net';
        setting.Log_Exceptions__c = true;        
        insert setting;
        
        Custom_Apex_Error_Handler__c setting2 = new Custom_Apex_Error_Handler__c();
        setting2.Name = 'CustomSettingNameTest2';
        setting2.Email__c = 'test2@testernovoidwork.net';
        setting2.Single_Apex_Class__c = 'TestTestTest';
        setting2.Log_Exceptions__c = true;        
        insert setting2;
        
        SG_ErrorHelper.doLogError('ApexClass','Exception',new Set<String>{setting.Email__c,setting2.Email__c});
    }
    
}