force-app/main/default/objects/Contact_Role_Validation_Setting__mdt/Contact_Role_Validation_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Used to validate Opportunity Contact Roles</description>
    <label>Contact Role Validation Setting</label>
    <pluralLabel>Contact Role Validation Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact_Role_Validation_Setting__mdt/fields/Comparison__c.field-meta.xml
<CustomField>
    <fullName>Comparison__c</fullName>
    <label>Comparison</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>equals</fullName>
                <default>true</default>
                <label>equals</label>
            </value>
            <value>
                <fullName>not equals</fullName>
            </value>
            <value>
                <fullName>less than</fullName>
            </value>
            <value>
                <fullName>less than or equals</fullName>
            </value>
            <value>
                <fullName>greater than</fullName>
            </value>
            <value>
                <fullName>greater than or equals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Role_Validation_Setting__mdt/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <description>How many of the particular Role do you need to compare? (If Comparison is &quot;less than&quot; then this would be if the Number of Roles is &lt; Count then thrown an error)</description>
    <inlineHelpText>How many of the particular Role do you need to compare? (If Comparison is &quot;less than&quot; then this would be if the Number of Roles is &lt; Count then thrown an error)</inlineHelpText>
    <label>to this Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact_Role_Validation_Setting__mdt/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>What error message do you want to display to the end user?</description>
    <inlineHelpText>What error message do you want to display to the end user?</inlineHelpText>
    <label>then display this Error Message</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Role_Validation_Setting__mdt/fields/Field_To_Check__c.field-meta.xml
<CustomField>
    <fullName>Field_To_Check__c</fullName>
    <defaultValue>&quot;StageName&quot;</defaultValue>
    <description>What field on the Opportunity should trigger when to validate the Roles? Must be the API Field Name (e.g. My_Custom_Field__c NOT My Custom Field)</description>
    <inlineHelpText>What field on the Opportunity should trigger when to validate the Roles? Must be the API Field Name (e.g. My_Custom_Field__c NOT My Custom Field)</inlineHelpText>
    <label>If this field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Role_Validation_Setting__mdt/fields/Field_Value_to_Check__c.field-meta.xml
<CustomField>
    <fullName>Field_Value_to_Check__c</fullName>
    <description>What is the value of the API Field Name To Check field? (example: Yes or maybe Closed/Won)</description>
    <inlineHelpText>What is the value of the API Field Name To Check field? (example: Yes or maybe Closed/Won)</inlineHelpText>
    <label>has this value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Role_Validation_Setting__mdt/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Name of the Role for the Contact Role that should be summed for checking/validating. Use &quot;ANY&quot; to count all Roles, use &quot;IsPrimary&quot; to ensure there is a Primary Contact.</description>
    <inlineHelpText>Name of the Role for the Contact Role that should be summed for checking/validating. Use &quot;ANY&quot; to count all Roles, use &quot;IsPrimary&quot; to ensure there is a Primary Contact.</inlineHelpText>
    <label>then count this Role</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Role_Validation_Setting__mdt/fields/Role_Object__c.field-meta.xml
<CustomField>
    <fullName>Role_Object__c</fullName>
    <label>Role Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SG_ContactRoleValidationHelper_Test.cls
/**********************************************************************
* Name:   	SG_ContactRoleValidationHelper_Test
* Author: 	Strategic Growth, Inc. (www.strategicgrowthinc.com)
* Date: 	28-Aug-2018
* ======================================================
* ======================================================
* Purpose: The purpose of this class is to                                                            
* 
* ======================================================
* ======================================================
* History:                                                            
* VERSION	DATE            INITIALS	DESCRIPTION/FEATURES ADDED
* 1.0     	28-Aug-2018     CS			Initial Development
* 1.01      29-Aug-2018     FMF         Convert to use metadata instead of custom settings
*   
***********************************************************************/


@IsTest
private class SG_ContactRoleValidationHelper_Test
{
    @TestSetup
    public static void createData() {
        SG_TestDataGenerator tdg = new SG_TestDataGenerator();
        tdg.contactNum = 2;
        tdg.opptyNum = 2;
        tdg.initAllTestData();
    }

    static testMethod void positiveUnitTestNotEquals() {
        Opportunity o = [ SELECT ID, StageName
                        FROM Opportunity
                        LIMIT 1 ];

        Contact c = [ SELECT ID
                    FROM Contact
                    LIMIT 1 ];

        // workaround the impossibility of inserting metadata
        String theRole = 'Project Manager';
        String rvsData = '[ { "Role_Object__c":"OpportunityContactRole", "Role__c":"' + theRole + '"'
                        + ', "Field_To_Check__c":"StageName", "Field_Value_To_Check__c":"' + o.StageName
                        + '", "Error_Message__c":"Test Error", "Comparison__c":"not equals"'
                        + ', "Count__c":"1" }'
                        + ', { "Role_Object__c":"OpportunityContactRole", "Role__c":"Executive Sponsor"'
                        + ', "Field_To_Check__c":"StageName", "Field_Value_To_Check__c":"Proposal/Price Quote"'
                        + ', "Error_Message__c":"Cannot set stage to price quote", "Comparison__c":"not equals"'
                        + ', "Count__c":"1" } ]';
        SG_ContactRoleValidationHelper.roleValidationSettings = (List<Contact_Role_Validation_Setting__mdt>)
                JSON.deserialize( rvsData, List<Contact_Role_Validation_Setting__mdt>.class );

        List<Contact_Role_Validation_Setting__mdt> rvsAssert =
                    SG_ContactRoleValidationHelper.getCustomSettings( o, 'OpportunityContactRole' );
        System.assertEquals( 1, rvsAssert.size() );

        Boolean error = false;

        OpportunityContactRole ocRole = new OpportunityContactRole();
        ocRole.Role = theRole;
        ocRole.ContactId = c.Id;
        ocRole.OpportunityId = o.Id;
        insert ocRole;

        // emulate opportunity trigger running once
        Map<Id, Opportunity> opptyMap = new Map<Id, Opportunity> { o.ID => o };
        SG_ContactRoleValidationHelper.validateOpportunityContactRolesHelper( opptyMap );

        try
        {
            update o;
            error = false;
        }
        catch( Exception exp )
        {
            error = true;
            System.debug( exp.getMessage() + ' - ' + exp.getStackTraceString() );
        }
        System.assertEquals( false, error );
    }

    static testMethod void positiveUnitNotEquals_NoTrigger()
    {
        Opportunity o = [ SELECT ID, StageName
        FROM Opportunity
        LIMIT 1 ];

        Contact c = [ SELECT ID
        FROM Contact
        LIMIT 1 ];

        // workaround the impossibility of inserting metadata
        String theRole = 'Project Manager';
        String rvsData = '[ { "Role_Object__c":"OpportunityContactRole", "Role__c":"' + theRole + '"'
                + ', "Field_To_Check__c":"StageName", "Field_Value_To_Check__c":"' + o.StageName
                + '", "Error_Message__c":"Test Error", "Comparison__c":"not equals"'
                + ', "Count__c":"1" }'
                + ', { "Role_Object__c":"OpportunityContactRole", "Role__c":"Executive Sponsor"'
                + ', "Field_To_Check__c":"StageName", "Field_Value_To_Check__c":"Proposal/Price Quote"'
                + ', "Error_Message__c":"Cannot set stage to price quote", "Comparison__c":"not equals"'
                + ', "Count__c":"1" } ]';
        SG_ContactRoleValidationHelper.roleValidationSettings = (List<Contact_Role_Validation_Setting__mdt>)
                JSON.deserialize( rvsData, List<Contact_Role_Validation_Setting__mdt>.class );

        List<Contact_Role_Validation_Setting__mdt> rvsAssert =
                SG_ContactRoleValidationHelper.getCustomSettings( o, 'OpportunityContactRole' );
        System.assertEquals( 1, rvsAssert.size() );

        // emulate opportunity trigger running once
        Map<Id, Opportunity> opptyMap = new Map<Id, Opportunity> { o.ID => o };
        Boolean error = SG_ContactRoleValidationHelper.validateOpportunityContactRolesHelper( opptyMap );

        system.assertEquals( true, error );

        OpportunityContactRole ocRole = new OpportunityContactRole();
        ocRole.Role = theRole;
        ocRole.ContactId = c.Id;
        ocRole.OpportunityId = o.Id;
        ocRole.IsPrimary = true;
        insert ocRole;

        error = SG_ContactRoleValidationHelper.validateOpportunityContactRolesHelper( opptyMap );

        system.assertEquals( false, error );
    }

    static testMethod void positiveUnitEquals_NoTrigger() {

        Opportunity o = [ SELECT ID, StageName
        FROM Opportunity
        LIMIT 1 ];

        Contact c = [ SELECT ID
        FROM Contact
        LIMIT 1 ];

        // workaround the impossibility of inserting metadata
        String theRole = 'Project Manager';
        String rvsData = '[ { "Role_Object__c":"OpportunityContactRole", "Role__c":"' + theRole + '"'
                + ', "Field_To_Check__c":"StageName", "Field_Value_To_Check__c":"' + o.StageName
                + '", "Error_Message__c":"Test Error", "Comparison__c":"equals"'
                + ', "Count__c":"1" }'
                + ', { "Role_Object__c":"OpportunityContactRole", "Role__c":"Executive Sponsor"'
                + ', "Field_To_Check__c":"StageName", "Field_Value_To_Check__c":"Proposal/Price Quote"'
                + ', "Error_Message__c":"Cannot set stage to price quote", "Comparison__c":"not equals"'
                + ', "Count__c":"1" } ]';
        SG_ContactRoleValidationHelper.roleValidationSettings = (List<Contact_Role_Validation_Setting__mdt>)
                JSON.deserialize( rvsData, List<Contact_Role_Validation_Setting__mdt>.class );

        List<Contact_Role_Validation_Setting__mdt> rvsAssert =
                SG_ContactRoleValidationHelper.getCustomSettings( o, 'OpportunityContactRole' );
        System.assertEquals( 1, rvsAssert.size() );

        OpportunityContactRole ocRole = new OpportunityContactRole();
        ocRole.Role = theRole;
        ocRole.ContactId = c.Id;
        ocRole.OpportunityId = o.Id;
        insert ocRole;

        // emulate opportunity trigger running once
        Map<Id, Opportunity> opptyMap = new Map<Id, Opportunity> { o.ID => o };
        Boolean error = SG_ContactRoleValidationHelper.validateOpportunityContactRolesHelper( opptyMap );

        system.assertEquals( true, error );
    }
}