force-app/main/default/objects/Contact_Role_Validation_Setting__mdt/Contact_Role_Validation_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Used to validate Opportunity Contact Roles</description>
    <label>Contact Role Validation Setting</label>
    <pluralLabel>Contact Role Validation Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact_Role_Validation_Setting__mdt/fields/Comparison__c.field-meta.xml
<CustomField>
    <fullName>Comparison__c</fullName>
    <label>Comparison</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>equals</fullName>
                <default>true</default>
                <label>equals</label>
            </value>
            <value>
                <fullName>not equals</fullName>
            </value>
            <value>
                <fullName>less than</fullName>
            </value>
            <value>
                <fullName>less than or equals</fullName>
            </value>
            <value>
                <fullName>greater than</fullName>
            </value>
            <value>
                <fullName>greater than or equals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Role_Validation_Setting__mdt/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <description>How many of the particular Role do you need to compare? (If Comparison is &quot;less than&quot; then this would be if the Number of Roles is &lt; Count then thrown an error)</description>
    <inlineHelpText>How many of the particular Role do you need to compare? (If Comparison is &quot;less than&quot; then this would be if the Number of Roles is &lt; Count then thrown an error)</inlineHelpText>
    <label>to this Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact_Role_Validation_Setting__mdt/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>What error message do you want to display to the end user?</description>
    <inlineHelpText>What error message do you want to display to the end user?</inlineHelpText>
    <label>then display this Error Message</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Role_Validation_Setting__mdt/fields/Field_To_Check__c.field-meta.xml
<CustomField>
    <fullName>Field_To_Check__c</fullName>
    <defaultValue>&quot;StageName&quot;</defaultValue>
    <description>What field on the Opportunity should trigger when to validate the Roles? Must be the API Field Name (e.g. My_Custom_Field__c NOT My Custom Field)</description>
    <inlineHelpText>What field on the Opportunity should trigger when to validate the Roles? Must be the API Field Name (e.g. My_Custom_Field__c NOT My Custom Field)</inlineHelpText>
    <label>If this field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Role_Validation_Setting__mdt/fields/Field_Value_to_Check__c.field-meta.xml
<CustomField>
    <fullName>Field_Value_to_Check__c</fullName>
    <description>What is the value of the API Field Name To Check field? (example: Yes or maybe Closed/Won)</description>
    <inlineHelpText>What is the value of the API Field Name To Check field? (example: Yes or maybe Closed/Won)</inlineHelpText>
    <label>has this value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Role_Validation_Setting__mdt/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Name of the Role for the Contact Role that should be summed for checking/validating. Use &quot;ANY&quot; to count all Roles, use &quot;IsPrimary&quot; to ensure there is a Primary Contact.</description>
    <inlineHelpText>Name of the Role for the Contact Role that should be summed for checking/validating. Use &quot;ANY&quot; to count all Roles, use &quot;IsPrimary&quot; to ensure there is a Primary Contact.</inlineHelpText>
    <label>then count this Role</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Role_Validation_Setting__mdt/fields/Role_Object__c.field-meta.xml
<CustomField>
    <fullName>Role_Object__c</fullName>
    <label>Role Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SG_ContactRoleValidationHelper.cls
/**********************************************************************
* Name:   	SG_ContactRoleValidationHelper
* Author: 	Strategic Growth, Inc. (www.strategicgrowthinc.com)
* Date: 	28-Aug-2018
* ======================================================
* ======================================================
* Purpose: The purpose of this class is to                                                            
* 
* ======================================================
* ======================================================
* History:                                                            
* VERSION	DATE            INITIALS	DESCRIPTION/FEATURES ADDED
* 1.0     	28-Aug-2018     CS			Initial Development
* 1.01      29-Aug-2018     FMF         Convert to use metadata instead of custom settings
*   
***********************************************************************/


/* To Use this code create or update existing Opportunity Trigger with this code

    System.debug( 'OpportunityTrigger:RoleValidationHelper' );

	if( Trigger.isAfter && Trigger.isUpdate )
	{
		System.debug( 'Calling SG_ContactRoleValidationHelper' );
		SG_ContactRoleValidationHelper.validateOpportunityContactRolesHelper( Trigger.newMap );
	}


 */

public without sharing class SG_ContactRoleValidationHelper
{

    public static List<Contact_Role_Validation_Setting__mdt> roleValidationSettings {
        get {
            if( roleValidationSettings == null ) {
                roleValidationSettings =
                            [ SELECT ID, Comparison__c, Field_Value_to_Check__c, Field_To_Check__c
                                    , Role_Object__c, Role__c, Error_Message__c, Count__c
                            FROM Contact_Role_Validation_Setting__mdt ];
            }
            return roleValidationSettings;
        }
        set;
    }

    public static List<Contact_Role_Validation_Setting__mdt> getCustomSettings( Opportunity oppty, String roleObject )
    {
        List<Contact_Role_Validation_Setting__mdt> applicableValidationSettings =
                new List<Contact_Role_Validation_Setting__mdt>();

        for( Contact_Role_Validation_Setting__mdt rvs : roleValidationSettings )
        {
            try
            {
                String fieldValue = ( String ) oppty.get( rvs.Field_To_Check__c );
                if( rvs.Role_Object__c.equalsIgnoreCase( roleObject )
                            && fieldValue != null
                            && fieldValue.equalsIgnoreCase( rvs.Field_Value_To_Check__c ) )
                {
                    applicableValidationSettings.add( rvs );
                }
            }
            catch( Exception exp )
            {
                // The main exception will be if the field doesn't exist or null values
                System.debug( exp );
            }
        }

        System.debug( '@@@ getCustomSettings : applicableValidationSettings ' + applicableValidationSettings );
        return applicableValidationSettings;
    }

    public static Boolean validateOpportunityContactRolesHelper( Map<Id, Opportunity> opptyMap )
    {
        Boolean atLeastOneValidationError = false;

        System.debug( 'validateOpportunityContactRolesHelper BEGIN' );

        Map<Id,Map<String,Double>> opptyIdToRoleToCount = new Map<Id,Map<String,Double>>();

        // NOTE:  it is not possible to add an OpportunityContactRole with null Role
        //        AND Role <> NULL
        List<AggregateResult> resultList =
                [ SELECT OpportunityId, Role, count( Id ) RowCount
                FROM OpportunityContactRole
                WHERE OpportunityId IN :opptyMap.keySet()
                GROUP BY OpportunityId, Role ];

        // organize the counts in a map of counts per role indexed by oppty id
        if( resultList != null && resultList.size() > 0 )
        {
            for( AggregateResult ar : resultList )
            {
                System.debug( 'looking at aggregate: ' + ar );

                Id opptyId = ( Id ) ar.get( 'OpportunityId' );
                String role = ( String ) ar.get( 'Role' );
                Double rowCount = ( Double ) ar.get( 'RowCount' );

                System.debug( 'OpptyId = ' + opptyId );
                System.debug( 'Role = ' + role );
                System.debug( 'RowCount = ' + rowCount );

                Map<String,Double> roleToCount = opptyIdToRoleToCount.get( opptyId );

                if( roleToCount == null )
                {
                    roleToCount = new Map<String,Double>();
                }

                roleToCount.put( role, rowCount );

                // save count for all roles
                Double allCount = roleToCount.get( 'ANY' );
                if( allCount == null ) {
                    allCount = 0;
                }
                allCount = allCount + rowCount;
                roleToCount.put( 'ANY', allCount );

                opptyIdToRoleToCount.put( opptyId, roleToCount );
            }
        }

        system.debug( 'opptyIdToRoleToCount (before primary) = ' + opptyIdToRoleToCount );

        List<OpportunityContactRole> contactRoles =
        [ SELECT OpportunityId, IsPrimary
        FROM OpportunityContactRole
        WHERE OpportunityId IN :opptyMap.keySet()
        ];

        if(contactRoles != null && contactRoles.size() > 0)
        {
            for( OpportunityContactRole contactRole : contactRoles )
            {
                System.debug( 'looking at contactRole: ' + contactRole );

                if(contactRole.IsPrimary)
                {
                    Id opptyId = contactRole.OpportunityId;
                    String role = 'IsPrimary';
                    Double rowCount = 1;

                    System.debug('OpptyId = ' + opptyId);
                    System.debug('Role = ' + role);
                    System.debug('RowCount = ' + rowCount);

                    Map<String, Double> roleToCount = opptyIdToRoleToCount.get(opptyId);

                    if (roleToCount == null)
                    {
                        roleToCount = new Map<String, Double>();
                    }

                    roleToCount.put(role, rowCount);

                    opptyIdToRoleToCount.put(opptyId, roleToCount);
                }
            }
        }

        system.debug( 'opptyIdToRoleToCount (with primary) = ' + opptyIdToRoleToCount );

        for( Opportunity o : opptyMap.values() )
        {
            System.debug( 'o = ' + o );

            Map<String,Double> roleToCount = new Map<String,Double>();

            if( opptyIdToRoleToCount.containsKey( o.Id ) )
            {
                roleToCount = opptyIdToRoleToCount.get( o.Id );
            }

            List<Contact_Role_Validation_Setting__mdt> applicableValidationSettings =
                            getCustomSettings( o, 'OpportunityContactRole' );
            System.debug( 'applicableValidationSettings = ' + applicableValidationSettings );

            for( Contact_Role_Validation_Setting__mdt customSetting : applicableValidationSettings )
            {
                System.debug( 'customSetting = ' + customSetting ); //Project Manager = 1
                if( customSetting.Role__c == null ) {
                    continue;
                }

                Double rowCount = 0;
                if( roleToCount.containsKey( customSetting.Role__c ) )
                {
                    rowCount = roleToCount.get( customSetting.Role__c );
                }
                System.debug( 'rowCount = ' + rowCount );
                System.debug( 'customSetting.Count__c = ' + customSetting.Count__c );

                Boolean validationError = false;

                // NOTE:  better test coverage this way
                Map<String, Boolean> comparisonMap = new Map<String, Boolean> {
                        'equals' => ( rowCount == customSetting.Count__c )
                        , 'not equals' => ( rowCount != customSetting.Count__c )
                        , 'less than' => ( rowCount < customSetting.Count__c )
                        , 'greater than' => ( rowCount > customSetting.Count__c )
                        , 'less than or equals' => ( rowCount <= customSetting.Count__c )
                        , 'greater than or equals' => ( rowCount >= customSetting.Count__c )
                };

                validationError = comparisonMap.get( customSetting.Comparison__c );
                System.debug( 'validationError for ' + customSetting.Comparison__c + ' = ' + validationError );

                if( validationError == true )
                {
                    atLeastOneValidationError = true;
                    o.addError( customSetting.Error_Message__c );
                    System.debug( 'added error = ' + customSetting.Error_Message__c );
                }
            }
        }

        return atLeastOneValidationError;
    }

}