force-app/main/default/objects/ADG_SfapiConfig__c/ADG_SfapiConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ADG SFAPI Config</label>
</CustomObject>

force-app/main/default/objects/ADG_SfapiConfig__c/fields/apiKey__c.field-meta.xml
<CustomField>
    <fullName>apiKey__c</fullName>
    <defaultValue>&quot;edb0e577-faa6-44a9-ac92-fb47d62e5fc7&quot;</defaultValue>
    <label>API Key</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ADG_SfapiConfig__c/fields/baseUrl__c.field-meta.xml
<CustomField>
    <fullName>baseUrl__c</fullName>
    <defaultValue>&quot;https://ihapi.adgus.net:6710&quot;</defaultValue>
    <label>Base Url</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community__c/Community__c.object-meta.xml
<CustomObject>
    <label>Community</label>
    <nameField>
        <label>Community</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Community__c/fields/Builder__c.field-meta.xml
<CustomField>
    <fullName>Builder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Builder</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Communities</relationshipLabel>
    <relationshipName>Sub_Divisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community__c/fields/Field_Service_Manager__c.field-meta.xml
<CustomField>
    <fullName>Field_Service_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Must be Service Resource</inlineHelpText>
    <label>Field Service Manager</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipName>Communities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Entity__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Austin</fullName>
            </value>
            <value>
                <fullName>Charleston</fullName>
            </value>
            <value>
                <fullName>Charlotte</fullName>
            </value>
            <value>
                <fullName>Colorado Springs</fullName>
            </value>
            <value>
                <fullName>Corpus Christi</fullName>
            </value>
            <value>
                <fullName>Columbia</fullName>
            </value>
            <value>
                <fullName>Denver</fullName>
            </value>
            <value>
                <fullName>DFW</fullName>
            </value>
            <value>
                <fullName>Fayetteville</fullName>
            </value>
            <value>
                <fullName>Grafton</fullName>
            </value>
            <value>
                <fullName>Greensboro</fullName>
            </value>
            <value>
                <fullName>Greenville</fullName>
            </value>
            <value>
                <fullName>Hilton Head</fullName>
            </value>
            <value>
                <fullName>Houston</fullName>
            </value>
            <value>
                <fullName>Indianapolis</fullName>
            </value>
            <value>
                <fullName>Loveland</fullName>
            </value>
            <value>
                <fullName>Myrtle Beach</fullName>
            </value>
            <value>
                <fullName>Nashville</fullName>
            </value>
            <value>
                <fullName>North Carolina</fullName>
            </value>
            <value>
                <fullName>Peninsula</fullName>
            </value>
            <value>
                <fullName>Phoenix</fullName>
            </value>
            <value>
                <fullName>Raleigh</fullName>
            </value>
            <value>
                <fullName>Salt Lake City</fullName>
            </value>
            <value>
                <fullName>San Antonio</fullName>
            </value>
            <value>
                <fullName>San Marcos</fullName>
            </value>
            <value>
                <fullName>South Carolina</fullName>
            </value>
            <value>
                <fullName>Tucson</fullName>
            </value>
            <value>
                <fullName>Wilmington</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestAdgSetup.cls
@isTest
public class TestAdgSetup {
    public static void Setup() {

        ADG_SfapiConfig__c setting = new ADG_SfapiConfig__c();
        setting.Name = 'ADG SFAPI Config';
        setting.apiKey__c = '123456789';
        setting.baseUrl__c = 'https://ihapi.adgus.net:6710';
        insert setting;

        Profile profile = [SELECT Id FROM Profile WHERE Name = '#Custom: Field Service Manager' LIMIT 1];

        User user = new User(
            Username = 'testUser@adgus.net',
            LastName = 'Doe',
            Email = 'testUser@adgus.net',
            Alias = 'test',
            TimeZoneSidKey = 'America/Chicago',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = profile.id,
            LanguageLocaleKey = 'en_US'
        );
        insert user;
        
        ServiceResource fieldServiceManager = new ServiceResource(
            Name = 'Test FieldServiceManager',
            RelatedRecordId = user.id
        );
        insert fieldServiceManager;

        Account builder = new Account(
            Name = 'builder',
            Account_Short_Name__c = 'Builder Short Name',
            Integration_Key_Account__c = 'FLR_BLD_RFMS:4549'
        );
        insert builder;

        Community__c community = new Community__c(
            Name = 'community',
            Builder__c = builder.id,
            Location__c = 'DFW',
            Field_Service_Manager__c = fieldServiceManager.id
        );
        insert community;

        Asset house = new Asset(
            Name = 'identifier',
            AccountId = builder.id,
            Community__c = community.id,
            Lot_Block__c = 'identifier',
            Field_Service_Manager__c = fieldServiceManager.id
        );
        insert house;

        ADG_JobPathCalloutMockup hcm = new ADG_JobPathCalloutMockup();
        hcm.body = house.Id;
        //hcm.assetId = house.Id;
        Test.setMock(HttpCalloutMock.class, hcm);
    }
}