force-app/main/default/objects/ADG_SfapiConfig__c/ADG_SfapiConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ADG SFAPI Config</label>
</CustomObject>

force-app/main/default/objects/ADG_SfapiConfig__c/fields/apiKey__c.field-meta.xml
<CustomField>
    <fullName>apiKey__c</fullName>
    <defaultValue>&quot;edb0e577-faa6-44a9-ac92-fb47d62e5fc7&quot;</defaultValue>
    <label>API Key</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ADG_SfapiConfig__c/fields/baseUrl__c.field-meta.xml
<CustomField>
    <fullName>baseUrl__c</fullName>
    <defaultValue>&quot;https://ihapi.adgus.net:6710&quot;</defaultValue>
    <label>Base Url</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Area__c/Area__c.object-meta.xml
<CustomObject>
    <label>Area</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Area ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Area__c/fields/Area_Note__c.field-meta.xml
<CustomField>
    <fullName>Area_Note__c</fullName>
    <label>Area Note</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Area__c/fields/Work_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order Line Item</label>
    <referenceTo>WorkOrderLineItem</referenceTo>
    <relationshipLabel>Areas</relationshipLabel>
    <relationshipName>Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community__c/Community__c.object-meta.xml
<CustomObject>
    <label>Community</label>
    <nameField>
        <label>Community</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Community__c/fields/Builder__c.field-meta.xml
<CustomField>
    <fullName>Builder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Builder</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Communities</relationshipLabel>
    <relationshipName>Sub_Divisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ADG_Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community__c/fields/Field_Service_Manager__c.field-meta.xml
<CustomField>
    <fullName>Field_Service_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Must be Service Resource</inlineHelpText>
    <label>Field Service Manager</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipName>Communities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Entity__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Austin</fullName>
            </value>
            <value>
                <fullName>Charleston</fullName>
            </value>
            <value>
                <fullName>Charlotte</fullName>
            </value>
            <value>
                <fullName>Colorado Springs</fullName>
            </value>
            <value>
                <fullName>Corpus Christi</fullName>
            </value>
            <value>
                <fullName>Columbia</fullName>
            </value>
            <value>
                <fullName>Denver</fullName>
            </value>
            <value>
                <fullName>DFW</fullName>
            </value>
            <value>
                <fullName>Fayetteville</fullName>
            </value>
            <value>
                <fullName>Grafton</fullName>
            </value>
            <value>
                <fullName>Greensboro</fullName>
            </value>
            <value>
                <fullName>Greenville</fullName>
            </value>
            <value>
                <fullName>Hilton Head</fullName>
            </value>
            <value>
                <fullName>Houston</fullName>
            </value>
            <value>
                <fullName>Indianapolis</fullName>
            </value>
            <value>
                <fullName>Loveland</fullName>
            </value>
            <value>
                <fullName>Myrtle Beach</fullName>
            </value>
            <value>
                <fullName>Nashville</fullName>
            </value>
            <value>
                <fullName>North Carolina</fullName>
            </value>
            <value>
                <fullName>Peninsula</fullName>
            </value>
            <value>
                <fullName>Phoenix</fullName>
            </value>
            <value>
                <fullName>Raleigh</fullName>
            </value>
            <value>
                <fullName>Salt Lake City</fullName>
            </value>
            <value>
                <fullName>San Antonio</fullName>
            </value>
            <value>
                <fullName>San Marcos</fullName>
            </value>
            <value>
                <fullName>South Carolina</fullName>
            </value>
            <value>
                <fullName>Tucson</fullName>
            </value>
            <value>
                <fullName>Wilmington</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Team__c/Community_Team__c.object-meta.xml
<CustomObject>
    <description>Team based sharing for Community with FSMs</description>
    <label>Community Team</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Community Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Team__c/fields/Community__c.field-meta.xml
<CustomField>
    <fullName>Community__c</fullName>
    <label>Community</label>
    <referenceTo>Community__c</referenceTo>
    <relationshipLabel>Community Teams</relationshipLabel>
    <relationshipName>Community_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Community_Team__c/fields/FSM__c.field-meta.xml
<CustomField>
    <fullName>FSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FSM</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Community Teams</relationshipLabel>
    <relationshipName>Community_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Team__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TILE</fullName>
            </value>
            <value>
                <fullName>CABINET</fullName>
            </value>
            <value>
                <fullName>CARPET</fullName>
            </value>
            <value>
                <fullName>COUNTERTOPS</fullName>
            </value>
            <value>
                <fullName>LAMINATE</fullName>
            </value>
            <value>
                <fullName>LVP</fullName>
            </value>
            <value>
                <fullName>SPECIALTY</fullName>
            </value>
            <value>
                <fullName>VINYL</fullName>
            </value>
            <value>
                <fullName>WOOD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ADG_Entity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Arlun</fullName>
    </customValue>
    <customValue>
        <fullName>AWC</fullName>
    </customValue>
    <customValue>
        <fullName>BWF</fullName>
    </customValue>
    <customValue>
        <fullName>Decor</fullName>
    </customValue>
    <customValue>
        <fullName>Dixie</fullName>
    </customValue>
    <customValue>
        <fullName>Floors</fullName>
    </customValue>
    <customValue>
        <fullName>Heritage</fullName>
    </customValue>
    <customValue>
        <fullName>Images</fullName>
    </customValue>
    <customValue>
        <fullName>Just Floors</fullName>
    </customValue>
    <customValue>
        <fullName>Kermans</fullName>
    </customValue>
    <customValue>
        <fullName>Malibu</fullName>
    </customValue>
    <customValue>
        <fullName>Markraft</fullName>
    </customValue>
    <customValue>
        <fullName>McDade</fullName>
    </customValue>
    <customValue>
        <fullName>Metro</fullName>
    </customValue>
    <customValue>
        <fullName>Nonn&apos;s</fullName>
    </customValue>
    <customValue>
        <fullName>NuWood</fullName>
    </customValue>
    <customValue>
        <fullName>Value Plus</fullName>
    </customValue>
    <customValue>
        <fullName>Vintage</fullName>
    </customValue>
    <customValue>
        <fullName>WCCV</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <masterLabel>ADG Entity</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ADG_TestSetup.cls
@isTest
public class ADG_TestSetup {
    public static void Setup() {
        ADG_SfapiConfig__c setting = new ADG_SfapiConfig__c();
        setting.Name = 'ADG SFAPI Config';
        setting.apiKey__c = '123456789';
        setting.baseUrl__c = 'https://ihapi.adgus.net:6710';
        insert setting;
        
        Profile profile = [
            SELECT Id
            FROM Profile
            WHERE Name = '#Custom: Field Service Manager'
            LIMIT 1
        ];
        
        User user = new User(
            Username = 'testUser@adgus.net',
            LastName = 'Doe',
            Email = 'testUser@adgus.net',
            Alias = 'test',
            TimeZoneSidKey = 'America/Chicago',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = profile.id,
            LanguageLocaleKey = 'en_US'
        );
        insert user;
        
        User user1 = new User(
            Username = 'testUser2@adgus.net',
            LastName = 'Doe',
            Email = 'testUser2@adgus.net',
            Alias = 'test',
            TimeZoneSidKey = 'America/Chicago',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = profile.id,
            LanguageLocaleKey = 'en_US'
        );
        insert user1;
        
        User user2 = new User(
            Username = 'testUser3@adgus.net',
            LastName = 'Doe',
            Email = 'testUser3@adgus.net',
            Alias = 'test',
            TimeZoneSidKey = 'America/Chicago',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = profile.id,
            LanguageLocaleKey = 'en_US'
        );
        insert user2;
        
        ServiceResource fieldServiceManager = new ServiceResource(
            Name = 'Test FieldServiceManager',
            RelatedRecordId = user.id
        );
        insert fieldServiceManager;
        
        ServiceResource fieldServiceManager1 = new ServiceResource(
            Name = 'Test FieldServiceManager2',
            RelatedRecordId = user1.id
        );
        insert fieldServiceManager1;
        
        ServiceResource fieldServiceManager2 = new ServiceResource(
            Name = 'Test FieldServiceManager3',
            RelatedRecordId = user2.id
        );
        insert fieldServiceManager2;
        
        Account account0 = new Account(
            Name = 'Builder Long Name, LLC CO.',
            Account_Short_Name__c = 'Builder Short Name',
            Integration_Key_Account__c = 'FLR_BLD_RFMS:4549'
        );
        insert account0;
        
        Id installerType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Installer Company').getRecordTypeId();
        Account account1 = new Account(
            Name = 'Jon Doe Contractors, LLC',
            Account_Short_Name__c = 'Jon Doe Short Name',
            RecordTypeId = installerType,
            Installer__c = 'ABC_RFMS:1111'
        );
        insert account1;
        System.debug('XXX Account1: ' + account1);
        
        Account account2 = new Account(
            Name = 'Jane Doe Contractors, LLC',
            Account_Short_Name__c = 'Jane Doe Short Name',
            RecordTypeId = installerType,
            Installer__c = 'ABC_RFMS:2222'
        );
        insert account2;
        
        Community__c community = new Community__c(
            Name = 'community',
            Builder__c = account0.id,
            Location__c = 'DFW',
            Field_Service_Manager__c = fieldServiceManager.id,
            Entity__c = 'Floors'
        );
        insert community;
        
        Asset house = new Asset(
            Name = 'identifier',
            AccountId = account0.id,
            Community__c = community.id,
            Lot_Block__c = 'identifier',
            Street__c = 'identifier',
            Field_Service_Manager__c = fieldServiceManager.Id
        );
        insert house;
        
        
        Contact contact1 = new Contact(
            Email = 'james.doe@adgus.net',
            FirstName = 'James',
            LastName = 'Doe',
            AccountId = account1.Id, // Has work orders attached to it.
            ContractPro_Account_Enabled__c = true
        );
        insert contact1;
        System.debug('XXX Contact1: ' + contact1);
        
        Contact contact2 = new Contact(
            Email = 'juan.doe@adgus.net',
            FirstName = 'Juan',
            LastName = 'Doe',
            AccountId = account2.Id, // Has no work orders attached to it.
            ContractPro_Account_Enabled__c = true
        );
        insert contact2;
        
        WorkOrder wo = new WorkOrder(
            AssetId = house.Id,
            AccountId = account0.Id,
            Community__c = community.Id,
            Field_Service_Manager__c = fieldServiceManager.id,
            Installer_Account__c = account1.id,
            Job_End_Day__c = date.today(),
            Start_Day__c = date.today(),
            Job_Type__c = 'CARPET'
        );
        insert wo;
        System.debug('XXX WorkOrder: ' + wo);
        
        WorkOrderLineItem woLine = new WorkOrderLineItem(
            WorkOrderId = wo.Id
        );
        insert woLine;
        
        Area__c areaRec = new Area__c(
            Work_Order_Line_Item__c = woLine.Id, 
            Area_Note__c = '<div class="notes-plain">This is a test note</div>'
        );
        insert areaRec;
        
        Community_Team__c ctm = new Community_Team__c(Community__c = community.Id, 
                                                      FSM__c = fieldServiceManager1.Id, 
                                                      Job_Type__c = 'CARPET');
        insert ctm;
        
        ADG_JobPathCalloutMockup hcm = new ADG_JobPathCalloutMockup();
        hcm.setJobPathsBody(house.Id);
        Test.setMock(HttpCalloutMock.class, hcm);
        
    }
    
    public static void messageTest() {
        ADG_SfapiConfig__c setting = new ADG_SfapiConfig__c();
        setting.Name = 'ADG SFAPI Config';
        setting.apiKey__c = '123456789';
        setting.baseUrl__c = 'https://ihapi.adgus.net:6710';
        insert setting;
        
        Profile profile = [
            SELECT Id
            FROM Profile
            WHERE Name = '#Custom: Field Service Manager'
            LIMIT 1
        ];
        
        User user = new User(
            Username = 'testUser@adgus.net',
            LastName = 'Doe',
            Email = 'testUser@adgus.net',
            Alias = 'test',
            TimeZoneSidKey = 'America/Chicago',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = profile.id,
            LanguageLocaleKey = 'en_US'
        );
        insert user;
        
        ServiceResource fieldServiceManager = new ServiceResource(
            Name = 'Test FieldServiceManager',
            RelatedRecordId = user.id
        );
        insert fieldServiceManager;
        
        Account account0 = new Account(
            Name = 'Builder Long Name, LLC CO.',
            Account_Short_Name__c = 'Builder Short Name',
            Integration_Key_Account__c = 'FLR_BLD_RFMS:4549'
        );
        insert account0;
        
        Account account1 = new Account(
            Name = 'Jon Doe Contractors, LLC',
            Account_Short_Name__c = 'Jon Doe Short Name'
        );
        insert account1;
        System.debug('XXX Account1: ' + account1);
        
        Account account2 = new Account(
            Name = 'Jane Doe Contractors, LLC',
            Account_Short_Name__c = 'Jane Doe Short Name');
        insert account2;
        
        Community__c community = new Community__c(
            Name = 'community',
            Builder__c = account0.id,
            Location__c = 'DFW',
            Field_Service_Manager__c = fieldServiceManager.id
        );
        insert community;
        
        Asset house = new Asset(
            Name = 'identifier',
            AccountId = account0.id,
            Community__c = community.id,
            Lot_Block__c = 'identifier',
            Street__c = 'identifier',
            Field_Service_Manager__c = fieldServiceManager.Id
        );
        insert house;    
        
        
        Contact contact1 = new Contact(
            Email = 'james.doe@adgus.net',
            FirstName = 'James',
            LastName = 'Doe',
            AccountId = account1.Id, // Has work orders attached to it.
            ContractPro_Account_Enabled__c = true
        );
        insert contact1;
        System.debug('XXX Contact1: ' + contact1);
        
        Contact contact2 = new Contact(
            Email = 'juan.doe@adgus.net',
            FirstName = 'Juan',
            LastName = 'Doe',
            AccountId = account2.Id, // Has no work orders attached to it.
            ContractPro_Account_Enabled__c = true
        );
        insert contact2;
        
        WorkOrder wo = new WorkOrder(
            AssetId = house.Id,
            AccountId = account0.Id,
            Community__c = community.Id,
            Field_Service_Manager__c = fieldServiceManager.id,
            Installer_Account__c = account1.id,
            Job_End_Day__c = date.today(),
            Start_Day__c = date.today(),
            Job_Type__c = 'CARPET'
        );
        insert wo;
        System.debug('XXX WorkOrder: ' + wo);
        
        WorkOrderLineItem woLine = new WorkOrderLineItem(
            WorkOrderId = wo.Id
        );
        insert woLine;
        
        Area__c areaRec = new Area__c(
            Work_Order_Line_Item__c = woLine.Id, 
            Area_Note__c = '<div class="notes-plain">This is a test note</div>'
        );
        insert areaRec;
    }
    
}