force-app/main/default/objects/Apex_Activation_Settings__c/Apex_Activation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings used to disable triggers on demand</description>
    <label>Apex Activation Settings</label>
</CustomObject>

force-app/main/default/objects/Apex_Activation_Settings__c/fields/Disable_All_Registered_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Disable_All_Registered_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable all triggers that have been coded to use this custom setting</description>
    <inlineHelpText>Disable all triggers that have been coded to use this custom setting</inlineHelpText>
    <label>Disable All Registered Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SG_ApexActivator.cls
/**********************************************************************
* Name:   	ApexActivator
* Author: 	Strategic Growth, Inc. (www.strategicgrowthinc.com)
* Date: 	04 MAR 2013
* ======================================================
* ======================================================
* Purpose: The purpose of this class is to help turn triggers on and off, if they subscribe to the custom setting                                                           
* 
* ======================================================
* ======================================================
* History:                                                            
* VERSION	DATE            INITIALS	DESCRIPTION/FEATURES ADDED
* 1.0     	04 MAR 2013     CS			Initial Development           
*   
***********************************************************************/


/* USAGE

	if(SG_ApexActivator.isDisabled('Disable Quote Triggers')
	{
		System.debug('Trigger disabled by Apex Activation Settings Custom Setting.');
		return;
	}

 */

public without sharing class SG_ApexActivator
{
	//Defaults to false
	public static Boolean isDisabled(String disable_Trigger_FieldName)
	{
		Boolean isDisabled = false;
		if(disable_Trigger_FieldName != null)
		{
			try
			{
				//Ensure we have a valid custom field name
				if(!disable_Trigger_FieldName.endsWith('__c'))
				{
					disable_Trigger_FieldName += '__c';
				}
				
				//Ensure we have a valid custom field name				
				disable_Trigger_FieldName = disable_Trigger_FieldName.replaceAll(' ', '_');
				
				Apex_Activation_Settings__c settings = Apex_Activation_Settings__c.getInstance();					
				
				if (settings != null && settings.Disable_All_Registered_Triggers__c == true || (Boolean)((SObject)settings).get(disable_Trigger_FieldName) == true)
				{
					isDisabled = true;				
				} 	
			}
			catch(Exception exp)
			{
				//Ignore
				SG_DisplayUtils.debug('SG_ApexActivator', 'isDisabled', 'IGNORE EXCEPTION' + SG_DisplayUtils.exceptionToString('SG_ApexActivator', exp));
			}
		}
		
		return isDisabled;
	}

}